### ISSUE TITLE
actionMeta.state.meta value differs depending on action type

### ISSUE THREAD

**Issue by Avocher** [statelyai/xstate#1047]
**Description**
When calling actions on `entry`, an `assign` action has the previous state nodes `meta` in `actionMeta.state` while a callback action has the entered state nodes `meta`.

**Expected Result**
I expected the `assign` action to have the `meta` object from the state node its entering, not the previous node.

**Actual Result**
`actionMeta.state.meta` value differs even if the actions are from the same action array.

**Reproduction**
https://codesandbox.io/s/compassionate-architecture-iev7m

**Additional context**
I had the idea to store mutual readonly values in the `meta` objects so that they could be "inherited" through the hierarchical state nodes and then used to calculate parts of the `context`, I'm not sure how good of an idea that is though...

**Comment by JackCA** [comment]
I'm encountering this now as well

**Comment by JackCA** [comment]
after digging further, this is probably https://github.com/davidkpiano/xstate/issues/603 in my case

**Comment by davidkpiano** [comment]
@JackCA Can you provide a reproducible example?

**Comment by markbjerke** [comment]
I thought assign actions were treated differently in that they were batched and executed on the previous state.  This was because the extended state is (potentially) used to determine the transitions destination state. So the behavior is correct?

--------------------------------------------------------------------------------------------------------------
Custom actions are always executed with regard to the next state in the transition. When a state transition has assign(...) actions, those actions are always batched and computed first, to determine the next state. This is because a state is a combination of the finite state and the extended state (context).

**Comment by Andarist** [comment]
`state` is no longer available in actions like that so this issue can be closed. We know and understand that there are some concerns related to that and we are still thinking/exploring ideas around this. They should be discussed in their own thread though.
