### ISSUE TITLE
Typing issues with transition actions

### ISSUE THREAD

**Issue by Perlkonig** [statelyai/xstate#1387]
**Description**
See discussion #1383. I'm using @xstate/immer, an "immerable" class as context, and immer's `assign` function to create the actions. When the context includes a potentially undefined class property, TypeScript typing errors occur *only when called as a transition action.* 

**Reproduction**
I've created a [CodeSandbox repo](https://codesandbox.io/s/xstate-transition-action-issue-b3hru) that demonstrates the error. Commenting out the offending line fixes the issues, as does moving the actions to enter/exit actions.

Thanks for your time!

**Comment by Andarist** [comment]
In the reported error we can observe this:
> Type 'AssignAction<MyContextClass, Events>' is not assignable to type 'Action<MyContextClass, LeaveEvent>'.

I don't believe this particular problem is caused by us stretching TS inference - this seems like a variance issue.

Let's check very simple assignability examples:
```ts
declare let a: AssignAction<MyContextClass, Events>
declare let b: AssignAction<MyContextClass, LeaveEvent>

b = a // error

declare let fn1: (ctx: MyContextClass, ev: Events) => void
declare let fn2: (ctx: MyContextClass, ev: LeaveEvent) => void

fn2 = fn1 // ok
```

Based on this we can get a more focused error from TS which leads us to:
```ts
declare let c: ActionFunction<MyContextClass, Events>
declare let d: ActionFunction<MyContextClass, LeaveEvent>

d = c // error
```

Why this doesn't type-check if we have already showcased that functions in a similar situation could be assigned? It's because if we rewrite the previous example to match `ActionFunction` more closely we get this:
```ts
declare let fn3: (ctx: MyContextClass, ev: Events, meta: { state: State<MyContextClass, Events> }) => void
declare let fn4: (ctx: MyContextClass, ev: LeaveEvent, meta: { state: State<MyContextClass, LeaveEvent> }) => void

fn4 = fn3 // error
```

And to simplify the situation with `State` we can reduce this further to:
```ts
// with generic class
class Cls<T> {
  public t: T
  constructor(t: T) {
    this.t = t
  }
}

declare let inst1: Cls<Events>
declare let inst2: Cls<LeaveEvent>

inst2 = inst1 // error

// with generic type
type Box<T> = {v: T}

declare let box1: Box<Events>
declare let box2: Box<LeaveEvent>

box2 = box1 // error

// with plain types
declare let foo: { v: Events }
declare let bar: { v: LeaveEvent }

bar = foo // error
```

So this happens because the third parameter of `ActionFunction` is **covariant** even though the `ActionFunction` itself is **contravariant**. Which are hard words that I don't even fully grasp myself 😅

**Comment by davidkpiano** [comment]
No longer reproducible with the latest versions (and some corrections): https://codesandbox.io/s/xstate-transition-action-issue-forked-9g7nw?file=/index.ts
