### ISSUE TITLE
`initialState` lifecycle seems to miss "after" transition.

### ISSUE THREAD

**Issue by nathanhammond** [statelyai/xstate#1403]
**Description**
State transitions in the `initialState` or immediately following do not seem to follow the full lifecycle. They instead appear to be possibly reentrant.

**Expected Result**
This state machine configuration should end up in an infinite loop. Each spawned `invocable-promise` should have `.stop()` called on it after 2 seconds, well before the 9 seconds that the promise takes to resolve.

**Actual Result**
The first `invocable-promise` spawned by `cancellable-promise` in `initialState` does not ever have `.stop()` called on it. Eventually this first `invocable-promise` resolves, pushing the parent state machine, `cancellable-promise`, to a `resolve`d state. All subsequent spawned machines (after the `initialState` one) do have `.stop()` successfully called on them.

**Reproduction**
Tested against 4.11, 4.12, and `HEAD` of `master`. All demonstrate the same behavior.

[4.11 test case](https://codesandbox.io/s/quizzical-greider-gf6q0)

**Additional context**
Converted to old syntax (away from `always`) to enable dropping it in the visualizer. Includes additional context from parent machines that is unused in the example code. Inline comments in the test cases.

**Comment by Andarist** [comment]
Thanks for reporting the issue and providing the repro case. I will try to look into it as soon as I can.

**Comment by Andarist** [comment]
This is currently broken on our side pretty badly I would say.

One problem is that we prioritize `assign` actions and they all get executed (within a single transition) before other actions - therefore when your stopping action gets called we have already assigned a new value to the `ctx.promise` (even though the order of those operations is defined to be the opposite). There is no clean workaround for this apart of splitting both things to 2 separate macro transitions (triggered by 2 external events). This has been fixed already on the `next` branch but as this behavior was documented we can't change it without releasing a new major version.

One thing that you shouldn't do is that you shouldn't call `.stop()` manually like this - we maintain parent/child relationship between those 2 machines and we keep references to each other in our internal structures. By calling `.stop()` manually you bypass our stopping logic and we have no chance to clean up after this - therefore this causes a memory leak.

How one should stop a spawned child then? That's an excellent question 😉 I believe that the best option right now is to use `stop` action. There is no documentation around this and also we don't really have good tests for this, so take this with a grain of salt.

This action accepts only string identifiers for the machine's children and to get that you have to rely on `pure` right now (as it gets access to `ctx` and can return other actions). This is a working example:
```js
actions.pure(ctx => actions.stop(ctx.promise.id))
```

I think we should both improve the story around this and provide good docs on how one should implement stopping spawned actors. cc @davidkpiano

**Comment by nathanhammond** [comment]
Good to know that I should turn my attention toward `next`! I'm happy to adopt the first version that can handle this—and do what I can to help it get here. You can at the least count on my contributing documentation for these details.

So: I switched over to `next` and trolled through test code to figure out how it would need to be wired up. [Here is a gist of the same test case reworked for `HEAD` of `next`.](https://gist.github.com/nathanhammond/f3f6639c3f60e03c787aeeda74389206) If you publish a `next` tag for `npm` from the `next` branch I'll move it into a sandbox.

There are numerous logs and comments in the gist in an attempt to make it clear what is happening. I would start by just running it to see the logs, and then read through the in-code comments.

Two apparent issues:
1. The first invoked promise does not trigger a done event, so the timeout catches and the `cancellable-promise` machine re-enters.
2. The `assign` for the later state (`cancellable-promise.spawn`) still runs before an `action` for the previous state (`cancellable-promise.reset`).

If you address the first of these it will mask the second one, but I can quickly create a new test case for that scenario. The second of these seems to imply that the ordering fixes in `next` may still have edge cases. Since these are in `next`, do you have any particular method by which you would prefer me file these issues?

(I didn't try to track down the `stop` stuff yet.)

**Comment by Andarist** [comment]
> Since these are in next, do you have any particular method by which you would prefer me file these issues?

Regular issues are OK for this IMHO, but since we already discuss this here - let's just keep it here as this issue has already some good context around this.

> The first invoked promise does not trigger a done event, so the timeout catches and the cancellable-promise machine re-enters.

I will have to investigate this.

> The assign for the later state (cancellable-promise.spawn) still runs before an action for the previous state (cancellable-promise.reset).

Right, my mistake - this is not a builtin action after all but a custom one. So it doesn't (at least currently) comply with the same rules as builtin ones.

Let me just explain a difference first - builtin actions are often "resolved" within `transition()` calls. This means they get **current** context and event values - based on which they can compute their final, resolved, "options" (for example targets for `send` actions). As mentioned before - this wasn't quite accurate in v4 because `assign` actions have a priority there and the are executed first and only then builtin actions are resolved.

Resolving builtin actions is supposed to be side effect free and thus it is safe to just resolve them within `transition()` as this API is supposed to be pure - it's bound to a pure machine and not to the impure interpreter.

We don't have a luxury of knowing impure/pure status of "custom actions" (written as inline functions) and quite frankly we don't need it, all of them can be considered as impure as they are intended to do side-effects.

All actions - including the builtin ones - are actually executed when `transition()` exits (when macrostep is done, if we use the SCXML nomenclature). The difference is that builtin ones could be "computed" beforehand and they have captured values from the resolving point in time which is not quite possible for the custom ones and we only have (currently) access to the very latest context/event values. This makes the whole thing less predictable and that's something we should strive to fight against as the XState is all about predictability. It also makes it harder, for no good reason, to generate accurate, correct typings for XState by tools like `xstate-codegen` with which we are experimenting.

I've observed this difference some time ago and mentioned it to @davidkpiano as harmful and we were discussing some potential solutions for this. Your issue is a good validation that it was not only my observation based on the intrinsic knowledge about the implementation of the codebase but that it affects real users in the wild.

Potential solutions that I'm seeing that would avoid a major re-architecture:
1. capture "current" values so they can be fed to custom actions when executing
2. execute as we go **if** we call `transition()` from the interpreter, could be implemented by providing a third argument to `transition` - something like `self` representing the caller

Other, more involved, solution would be to rethink how Machine and Interpreter APIs interact with each other - we want to cover both use cases (pure and impure) so we need to think about a design allowing this. Maybe it would be beneficial to split `Machine` into 2 separate APIs - `MachineConfig` and `Machine`? Where usually people would interact with `MachineConfig` and fed that to `Interpreter` and it would act as the impure caller whereas if one would like to get access to the pure transitions they could create `Machine`s and call its pure methods? The majority of the implementation would, of course, have to be shared - both would deal with a very similar problem and both would have to resolve transitions internally, the difference would just lie in purity and timing of certain things.

**Comment by nathanhammond** [comment]
> Have you tried using this in v4?
> ```js
> actions.pure(ctx => actions.stop(ctx.promise.id))
> ```

Quick response for now: I have not yet, but I intend to. Having read your most-recent note (just once, will need to re-read) it seems like being able to mark it as a "pure" action to send a `stop` might make this approach _almost_ work in `v4` (by getting rolled into the transition), excepting the hoisting of `assign`. My presumption, based upon the mental model I'm building, is that `ctx.promise.id` will still be `2` by the time `actions.stop` gets processed.

Further, it's possible that a "pure" action in `next`-land might also demonstrate the same semantics, solving what I describe as issue 2. Will try experimenting there as well.

No need to correct any misunderstandings I include here—I will discover them shortly. I'll report back tomorrow (UTC+8 afternoon) once I take a look at `stop` (in both `v4` and `next`).

**Comment by nathanhammond** [comment]
Quick update (but I should really stop looking at this for today):

In V4 (`HEAD`, to pick up #1401) using a `pure` action as you suggested appears to work as desired without leaking memory (profiled in Chrome). More tomorrow, still intending to write documentation for this.

As I learn more, it seems like this should maybe be broken down into subpieces, will revisit this list tomorrow:
- [ ] [V4] Documentation for `pure` actions. (@nathanhammond to write.)
- [ ] [V4] Documentation for `stop` actions. (@nathanhammond to write.)
- [ ] [V5] First invoked promise doesn't trigger `done` event.
- [ ] [V5] "Logical" ordering of actions. (Research project.)

(Nothing needed from you at this point, tomorrow still planning to explore pure actions in V5, and then write some documentation from my learnings.)

**Comment by Andarist** [comment]
> No need to correct any misunderstandings I include here—I will discover them shortly.

Can't help myself 😅 

I've tested `actions.pure(ctx => actions.stop(ctx.promise.id))` before posting it, so if I haven't misinterpreted something wrongly (I admit I go through issues very quickly, trying to be time-efficient) this should work. `pure` gets resolved with currentContext [here](https://github.com/davidkpiano/xstate/blob/ad3026d4309e9a1c719e09fd8c15cdfefce22055/packages/core/src/actions.ts#L633) so it should work OK for this case.

**Comment by nathanhammond** [comment]
Look at that race condition on us responding. 😜

**Comment by Andarist** [comment]
I strongly believe that this issue has been fixed on the `next` branch.
