### ISSUE TITLE
The xstate-test testContext type `unknown` is not able to be typed

### ISSUE THREAD

**Issue by CMCDragonkai** [statelyai/xstate#1598]
When using the `withEvents`, in the `exec` function, I want to give the `testContext` a specific type.

However if I use typescript, it complains that the type is incorrect.

```
  backupRestoreModel = backupRestoreModel.withEvents({
    GET_BACKUP: {
      exec: async(x: BackupRestoreService, e) => {
        console.log('WHAT IS x?', x);
        console.log('WHAT IS e?', e);
      }
    }
  });
```

The error is:

```
TSError: ⨯ Unable to compile TypeScript:
src/bin/backuprestore.ts:17:7 - error TS2322: Type '(x: BackupRestoreService, e: EventObject) => Promise<void>' is not assignable to type 'EventExecutor<unknown>'.
  Types of parameters 'x' and 'testContext' are incompatible.
    Type 'unknown' is not assignable to type 'BackupRestoreService'.

17       exec: async(x: BackupRestoreService, e) => {
         ~~~~
```

Only if I leave out the type, and also enable implicit nulls in tsconfig.json can I actually make use of it.

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by CMCDragonkai** [comment]
The xstate-test introduction... if used with typescript has this behaviour.

**Comment by Andarist** [comment]
I'm afraid this is not a **runnable** repro case. I understand that this might not be hard to set up and reproduce but we, maintainers, have multiple issues to handle at the same time and everything that allows us to jump right away into the problem helps us immensely. It also removes the most possibilities of miscommunication because with a runnable repro case we'd basically be able to inspect your **exact** situation whereas if we try to reproduce ourselves then we might not do that properly in terms of achieving the same situation.

**Comment by CMCDragonkai** [comment]
According to https://mariusschulz.com/blog/the-unknown-type-in-typescript

> The unknown type is only assignable to the any type and the unknown type itself. Intuitively, this makes sense: only a container that is capable of holding values of arbitrary types can hold a value of type unknown; after all, we don't know anything about what kind of value is stored in value.

I don't think this problem requires repro, it's a really trivial problem.

It's clearly stated that unknown type is only assignable to any or unknown.

I found the only solution I have is to reassign the `testContext` to `any`, or with explicit type assertions using `any`.

**Comment by Andarist** [comment]
Even a trivial problem might require a runnable repro case - or rather, providing one simplifies things. I don't understand why do you resist this, rather simple, request. We try to maintain the project in our spare time, helping a lot of people by doing this. I perfectly understand the problem itself but the root cause is what I'm after and this is not really explained here - beyond the basic conclusion that our types are causing this somewhere. To assess if this is intended behavior or a bug I really need to understand the whole picture and runnable repro case is the key to that. There is also the aspect that you could count on more people helping you if you would provide a runnable repro case - even I'm a maintainer and I've done a fair share of development/changes around the codebase the `@xstate/test` is not something I'm overly familiar with. Software (OSS or not) is usually a product of the work of many people - not everyone has the same knowledge about the project. It's also easy to forget stuff etc. So again - providing a runnable repro case allows me, or even others, help you out **quicker**. So if you expect getting help from anybody it is only reasonable to answer questions/requests regarding your problem from people that want to help you. 

Don't take this as rude, this is not my intention. I'd just like you to understand my perspective better.

**Comment by davidkpiano** [comment]
Sigh, okay I've created a repro here: https://codesandbox.io/s/infallible-browser-jjcin?file=/src/index.ts

I'm not seeing the error, though? Which version of TS are you running?

**Comment by Andarist** [comment]
And this is one of the things I've tried to communicate. If @CMCDragonkai would take time to prepare a runnable repro then David would not "waste" time by trying to reproduce without success. Providing a repro case is usually lowering communication barrier and we should always strive for that.
