### ISSUE TITLE
@xstate/test state.invoke is not called

### ISSUE THREAD

**Issue by dalwlad** [statelyai/xstate#1673]
**Description**
[`state.invoke`](https://xstate.js.org/docs/guides/communication.html#invoking-promises) is not called when the state machine is tested using `@xstate/test`

**Expected Result**
[`state.invoke`](https://xstate.js.org/docs/guides/communication.html#invoking-promises) is called when a state machine is tested using `@xstate/test` package

**Actual Result**
Services should be invoked when testing the state machine. There are cases where async operations need to be performed as part of the tests, when `@xstate/test` is used for running e2e tests of real applications. Mocking the data defeats the purpose here, it would be nice to be able to call such services by using the `invoke` api provided in the docs.

**Reproduction**

- [Codesandbox repro link](https://codesandbox.io/s/xstatetest-ondone-warning-forked-rl2fv?file=/src/index.js)

**Additional context**
- `@xstate/test@0.4.1`
- `xstate@4.14.1`

<details>
<summary>Repro code</summary>

```javascript
const { Machine: createMachine } = require("xstate");
const { createModel } = require("@xstate/test");

const machine = createMachine({
  id: "toggle",
  initial: "inactive",
  states: {
    inactive: {
      invoke: {
        id: "callMe",
        src: (context, event) => {
          return new Promise((resolve) => {
            console.log("I am not being called");
            resolve();
          });
        }
      },
      on: { TOGGLE: "active" }
    },
    active: {
      on: { TOGGLE: "inactive" }
    }
  }
});

const model = createModel(machine).withEvents({
  TOGGLE: {}
});

const execute = async (plans) => {
  plans.forEach((plan) => {
    console.log(plan.description);

    plan.paths.forEach(async (path) => {
      console.log("    " + path.description);

      await path.test({ ctx: "foo" });
    });
  });
};

(async function () {
  await execute(model.getSimplePathPlans());
})();
```
</details>

<details>
<summary>Console.log generated by the repro code</summary>

```
reaches state: "#toggle.inactive"  
    via  
reaches state: "#toggle.active"  
    via TOGGLE 
```
</details>

**Comment by dalwlad** [comment]
@davidkpiano Since the issue has been marked as an enhancement, I'm wondering if there are any other features of the state machines that are not working while using machines to drive e2e tests. I didn't find in the docs a place where this is explained, am I missing something obvious here?

**Comment by davidkpiano** [comment]
@dalwlad I'm working on this as part of the next version of `@xstate/test` https://github.com/statelyai/xstate/pull/3036/commits/4e2be879a289c8914ba36dcd05d5d402bac45516

**Comment by davidkpiano** [comment]
Actually, marking this as a wontfix, since machines used for testing (in model-based testing scenarios) differ than using `@xstate/test` to test actual machines.

The machine model used for MBT should be a statechart that represents states and transitions in your app in a pure sense, _without_ executing any side-effects of its own. For example, if you're testing a page loading data, you would not model that as an `invoke` in the statechart modeling your app. Instead, you should model that as a `loading` state that might have something like a `data.loaded` event, where the execution of that event is awaiting something to appear on screen that indicates that the data has loaded.

To test invocations in machines, you should use one of the strategies listed here: https://xstate.js.org/docs/guides/testing.html#testing-services

**Comment by nullbytesoftware** [comment]
> Actually, marking this as a wontfix, since machines used for testing (in model-based testing scenarios) differ than using `@xstate/test` to test actual machines.
> 
> The machine model used for MBT should be a statechart that represents states and transitions in your app in a pure sense, _without_ executing any side-effects of its own. For example, if you're testing a page loading data, you would not model that as an `invoke` in the statechart modeling your app. Instead, you should model that as a `loading` state that might have something like a `data.loaded` event, where the execution of that event is awaiting something to appear on screen that indicates that the data has loaded.
> 
> To test invocations in machines, you should use one of the strategies listed here: https://xstate.js.org/docs/guides/testing.html#testing-services

I was hoping to be able to use the same machine for testing as well. This makes it hard as I will have to recreate each machine I have in order to test it. 
Also If I make modifications to my machine that wont make my tests fail. I have to maintain the test machine and ensure they operate in a similar logic. 

Is there any work around to make the machine work with a test model as well?

**Comment by davidkpiano** [comment]
@nullbytesoftware Can you post this as a discussion in https://github.com/statelyai/xstate/discussions/new ?
