### ISSUE TITLE
onTransition does not fire after every transition

### ISSUE THREAD

**Issue by tomByrer** [statelyai/xstate#1767]
**Description**
`onTransition` does not fire with `always'

**Expected Result**
A few choices:
+ document that `onTransition` only fires when the "machine 'settles'" & keep behavior as-is
+ `onTransition` always fires, including with `always`
+ configure if `onTransition` fires with `always`, or make `onTransitionAlways`

**Reproduction**
https://tombyrer.github.io/cat-christmas/cat-christmas

**Additional context**
[reference issue](https://github.com/davidkpiano/xstate/issues/1685#issuecomment-749507365)

**Comment by davidkpiano** [comment]
What's your use-case for having `onTransition` (or a new method) fire with transient/eventless transitions?

If you want an action to happen, the appropriate place to put that action is on the eventless transition itself.

Eventless transitions are taken within the same "microstep", so conceptually, it's like wanting a callback whenever a transition happens here (pseudocode):

```js
function handleEvent() {
  doTransition();
  doAnotherTransition();
  doYetAnotherTransition();
}
```

If there were a hypothetical `onTransitionAlways` or `onMicrostep`, then it would be called 3 times, all at the exact same time; basically this:

```js
for (const transition of microstepTransitions) {
  callMicrostepCallback(transition);
}
```

Is this what you expect? Just trying to understand the use-cases here.

**Comment by tomByrer** [comment]
In my demo above, I assumed that all `always{}` were triggered in `onTransition`, where I was going to update the DOM. 

I don't have a strong use-case for `onTransitionAlways` right now; just brainstorming. There are workarounds, I don't *need* to have `it..

Better docs of how the current system works would help if you don't want to add ; I was not aware of 'microsteps' in XState until yesterday, despite referring to the docs & Discussions 100 times.

**Comment by Andarist** [comment]
I firmly believe that the issue presented here is sound. From my PoV, it's not about functional shortcomings (I don't have a use case that is not satisfied by the current APIs) but rather about semantic discrepancies.

If we call something a **transition** and we later provide the **onTransition** callback I would fully expect for it to be fired after every transition. Otherwise, we just end up confusing new learners because it's not obvious that this actually behaves differently. And as shown by the issue here - it's not a theoretical learning problem because @tomByrer (and myself in the past as well) has assumed a different behavior than the one that is currently implemented. This becomes even more of a problem because we've recommended using the `onTransition` to handle some logic **whenever** something happens (like getting a particular value in the context) in multiple issues - and currently some occurrences of the desired situation might be "skipped", which is not obvious.

I understand that this mainly~ comes from the fact that this is called after `machine.transition()` which actually resolves all microsteps but maybe then this method should not be called `transition` either? This is a low-level API and as such, I actually wouldn't mind a different resolution either - we could rethink if this actually should resolve all microsteps. Maybe it should be up to the interpreter to handle the resolution of the microsteps? From the final consumer's PoV this actually wouldn't matter much (unless they depend on the raw Machine API - but those users are already "advanced" so I don't mind requiring more of them). This could actually simplify various stuff like SCXML compatibility with action order & error handling, semantic correctness, and even visualization (I believe that representing microsteps on the visualization is also important for the reasoning process, at times it might not be obvious why we have jumped directly from A to B without seeing the whole "path")

**Comment by tomByrer** [comment]
While I do lean more towards Andarist's perspective of "confusing new learners" (like me :) ).  I want to provide counter perspective; skipping `always {}` does provide a neat way to separate out each 'thing to do' into individual steps, rather than having to combine an action step & timer step like I did with `play{}` state

**Comment by Andarist** [comment]
> skipping always {} does provide a neat way to separate out each 'thing to do' into individual steps, rather than having to combine an action step & timer step like I did with play{} state

Could you elaborate? Not sure if I 100% understand what do you mean in the context of this issue.

**Comment by tomByrer** [comment]
I ran into this issue again in my current project where chaining `always` seemed to not run sequentially, perhaps due to calling external machines / async functions.  So not only it is hard to debug, but I don't know how to sequence 'the XState way'; I'll either have to repeat code & use Promise/await, for force users into human await statements. ;)

> Could you elaborate?

I would like to separate each action into a single state, so they can be chained by other states.  My quiz program is too complex of an example, so I made a simple one:

This is a dice roller that acclimates sums and clear those sums.   I added a shortcut to reset-then-roll in one event.  You can see with this shortcut, the reset runs, but is not logged.

https://codesandbox.io/s/xstated6roller-rugv5?file=/src/index.js

**Comment by davidkpiano** [comment]
This will be coming to v5:

```js
// TENTATIVE API

service.onMicrostep(state => {
  // intermediate state
  console.log(state);
});
```

**Comment by tomByrer** [comment]
Ah, thanks David!

BTW, I assume XState tries to batch actions, even from different states, until it hits a transition it can not cross.  (As opposed to taking each state at a time.)
Am I correct?

**Comment by Andarist** [comment]
If you are referring to what events `onTransition` is being called with - this batching only applies to NULL events (aka always transitions) and raised events. If you send an event FOO to a machine and it specifies a regular `send` action in a matched transition(s) then this second event won't be "batched" for the purpose of `onTransition`.

**Comment by huan** [comment]
> Otherwise, we just end up confusing new learners because it's not obvious that this actually behaves differently. 

Yet a new learner here +1

Looking forward to using the `onMicrostep` in v5!

**Comment by ehuelsmann** [comment]
Looking forward for v5. My use-case is an external listener which knows the state machine will pass through a particular state. Because that state is an immediate state, the listener isn't notified and I need to listen for the next state being reached. This is a problem, because it encodes implementation knowledge in the listener.

**Comment by Andarist** [comment]
I'm wondering - why do you listen for this stuff instead of firing some action when entering a given state or something?

**Comment by ehuelsmann** [comment]
> I'm wondering - why do you listen for this stuff instead of firing some action when entering a given state or something?

It has to do with separation of concerns: the listener is a controller which coordinates multiple state machines. When a specific state transition in one machine happens, the controller may need to trigger an action on another state machine. If the state machine itself had that action coded, it would need to know about all other state machines (and those about this one), breaking separation of concerns, leading to tight integration.

**Comment by Andarist** [comment]
`onTransition` has been removed in v5. However, the alternative that we suggest using instead of it (`subscribe`) works in a similar way - that callback is fired after the state "settles". We'll have a way to inspect all transitions using the API focused on inspection. If that's not enough - please open a new discussion thread, explain why do you need it, etc.

**Comment by HKITYAN** [comment]
Where can I find document about the APIs for inspection?

**Comment by davidkpiano** [comment]
> Where can I find document about the APIs for inspection for nodejs program?

Writing these docs this weekend.

See the latest merged PR for the inspect API to see usage.
