### ISSUE TITLE
[xstate/fsm] Guarded transitions throw "(intermediate value) is not a function" error

### ISSUE THREAD

**Issue by jjenzz** [statelyai/xstate#1890]
**Description**

I'm using `@xstate/fsm` with `useMachine` from `@xstate/react/lib/fsm` and trying to guard a transition by passing the guard implementation to `useMachine` but it throws an error when triggering the event.

**Expected Result**

No error.

**Actual Result**

```
(intermediate value)(intermediate value)(intermediate value) is not a function
```

**Reproduction**

Click the button in the following sandbox:

https://codesandbox.io/s/nervous-mayer-8k4s8?file=/src/App.js

**Additional context**

I'm probably doing something completely wrong here. Any help would be super appreciated 😬

**Comment by jjenzz** [comment]
Ah, interesting! Thank you for the quick reply. Can I ask what you mean my parameterized? 🙈 

I thought you might have meant that they cannot be passed as opts to the `useMachine` hook but the comparison table says parameterized actions are not supported yet they work when I pass them via opts. My attempted process of elimination is failing me here 😅

**Comment by Andarist** [comment]
@davidkpiano dont we call actions/guards/whatever with some params as parametrized smth? Like in here:
```
actions: {
  type: 'nameOfTheAction',
  someParam: 42
}
```

@jjenzz only actions can be provided in the second argument right now:
https://github.com/davidkpiano/xstate/blob/e0fd12ac43be4508579ccbf1edb3c4d6c544d515/packages/xstate-fsm/src/index.ts#L121-L123

**Comment by davidkpiano** [comment]
> @davidkpiano dont we call actions/guards/whatever with some params as parametrized smth? Like in here:
> 
> ```
> actions: {
>   type: 'nameOfTheAction',
>   someParam: 42
> }
> ```


Ah, my mistake. Actions can be parameterized; guards cannot (yet).

**Comment by Andarist** [comment]
Right - this issue is about not being able to "provide" a guard implementation in the second argument of the `createMachine` from `@xstate/fsm`,  like it can be done for the `xstate` itself:
```js
createMachine({ /* ... */ }, {
  guards: {
    someGuard: () => true
  }
})
```

It seems that there might be some confusion about what this issue is about - I wasn't completely sure though because I wasn't sure if we both mean the same thing by "parametrized guards" (as if we stick to the example I have given this issue is not about parametrized guards in `@xstate/fsm` but rather about "provided guards", although we haven't really coined this term as much).

**Comment by jjenzz** [comment]
> This issue is about not being able to "provide" a guard implementation in the second argument of the `createMachine`

Exactly. That is the example I've shown in the CodeSandbox. I'm not passing any params as far as I know to the guard, just providing the implementation in the `useMachine` options.

Should that be working or would this be a feature request?

**Comment by Andarist** [comment]
Feature request. It should be fairly easy to implement and given that we support both guards and provided actions I think it would only make sense to support provided guards as well. Would you maybe like to contribute PR to this feature? Might be worth waiting for @davidkpiano's green light first though.

**Comment by davidkpiano** [comment]
> Feature request. It should be fairly easy to implement and given that we support both guards and provided actions I think it would only make sense to support provided guards as well. Would you maybe like to contribute PR to this feature? Might be worth waiting for @davidkpiano's green light first though.

I'm working on an implementation for the `@xstate/fsm` side right now 🏃

**Comment by Andarist** [comment]
Since on the `next` branch, we discontinued `@xstate/fsm` package (see [here](https://github.com/statelyai/xstate/pull/4265)) - I think that this issue can be closed now as it's no longer applicable. 

`@xstate/fsm` continues to work so you don't need to refactor your code if you care about its lightweight bundlesize.
