### ISSUE TITLE
Error invoke machine

### ISSUE THREAD

**Issue by AntonS86** [statelyai/xstate#2057]
Error! if the parent machine is stopped, and the invoke service has an exit - sandParent event, then the machines cannot be stopped.
```js
import { Machine, interpret, send, sendParent } from "xstate";

// Invoked child machine
const pongMachine = Machine({
  id: "pong",
  initial: "active",
  states: {
    active: {
      entry: sendParent("ENTRY_EVENT"),
      // The error is here!!!!!!!
      exit: sendParent("EXIT_EVENT"),
      on: {
        PING: {
          // Sends 'PONG' event to parent machine
          actions: sendParent("PONG", {
            delay: 1000
          })
        }
      }
    }
  }
});

// Parent machine
const pingMachine = Machine({
  id: "ping",
  initial: "active",
  states: {
    active: {
      invoke: {
        id: "pong",
        src: pongMachine
      },
      // Sends 'PING' event to child machine with ID 'pong'
      entry: send("PING", { to: "pong" }),
      on: {
        PONG: {
          actions: send("PING", {
            to: "pong",
            delay: 1000
          })
        }
      }
    }
  }
});

const service = interpret(pingMachine)
  .onTransition((s) => console.log(s))
  .start();
service.stop();
```

Please help me, I am using a library on a working project and cannot kill the running machines

https://codesandbox.io/s/xstate-typescript-template-forked-30nli?file=/src/index.ts:0-989

**Comment by davidkpiano** [comment]
The problem (on our end) is we're not resolving exit actions properly when a machine is stopped, since those exit actions are "out of band" and not tied to a specific transition that we can resolve to.

A simple fix would be to create an `'xstate.stop'` event, just as we have an `'xstate.start'` event. This gives us an event that we can resolve the action to (resolving it to the previous event is inaccurate).

Proof of concept PR here: #2058 cc. @Andarist

**Comment by AntonS86** [comment]
we also receive a warning if, when the car stops, we assign a context in the exit function.
https://codesandbox.io/embed/icy-tree-mjtg6?codemirror=1

**Comment by Andarist** [comment]
Note that it's generally better to stop actors using `stop` action, like this:
```js
exit: actions.pure(({ actor }) => [
  actions.stop(actor),
  actions.assign({ actor: null })
])
```

In the future (next major version) you won't have to wrap this in `pure` but right now this is necessary to work around an issue with `assign`s being always resolved first.

This, however, doesn't resolve your issue entirely - as in this scenario Interpreter executes those actions and it doesn't understand `assign` and `pure` since those are usually resolved within Machine. We can figure out how to workaround for this for the time being but I believe that it indicates a bigger problem in the current design and that we might need to reevaluate how this should be handled in the code in the long run.
