### ISSUE TITLE
createSchema<TContext>() type inference breaks down in some cases

### ISSUE THREAD

**Issue by VanTanev** [statelyai/xstate#2126]
**Description**
Since [xstate@4.17.0](https://github.com/davidkpiano/xstate/releases/tag/xstate%404.17.0) the `schema` property can be used instead of generic type arguments to `createMachine()` to provide Context / Event types. 

However, the first time I attempted to use it, it broke on a fairly trivial definition:
```typescript
import { createMachine, createSchema } from 'xstate'

type Context = { name: string}
type Event = { type: 'SAY_HELLO'}

createMachine({
  schema: {
    context: createSchema<{ name: string }>(),
    events: createSchema<{ type: 'SAY_HELLO' }>(),
  },
  context: {
    name: 'John Doe'
  },
  on: {
    SAY_HELLO: {
      // BROKEN, `ctx` is inferred as `any`
      actions: (ctx) => {
        alert(ctx.name)
      }
    }
  }
})
```

I have not explored more complex definitions.

**Reproduction**
[Typescript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQWQ8gC2ADs0AaFdLNAZULRAzgF84AzKCEOAcgA8AzjGo8AUKJgBPMGjgBhCMWx94AXkRxiGEGgBccIVBIBzZhOmyAogDc0SuOqRSZ+njQCCATQD6ACUsAMgEA8jxmqJjYeIQkaAAUCKJwBvSM+onJyciKyjD6EdR0BAwYADxIWjr6hiYsAHxxAJRkSZlotkoC+VTYRSXlcM56vB4+-kGh9U0tycwzKDloKumtyZXDPABSEATEcAAiEGhis-OKK5lwo36BIReXcAD0j3AAQgBKwQDSlgByq5l8DBgIounA4sgYHxGg46ogAZcMAAbNCwCFQgB060aCJYALMs1EzBxogKUXwRFIpQUSiWMAoNjsMAaGQWtOW8Mu61c212ByOJxYZ2I92S13Gd05D2ecAA6sF3l8aLigSDiGD0dDYVKHnBkaiYJqsdo0DjdQTMhazMTREA)

**Comment by Andarist** [comment]
I will be looking into this more later but it's somewhat weird because the IDE sees the "provided" type for the `actions` key there:
<img width="577" alt="Screenshot 2021-04-22 at 00 48 38" src="https://user-images.githubusercontent.com/9800850/115630627-9a5e4c80-a304-11eb-9dd0-c1e8296dd348.png">

So it's rather surprising that the IDE sees the correct thing but yet the type for the `ctx` ain't inferred properly from the context.

**Comment by Andarist** [comment]
After investigating this some more I was able to create a minimal repro case for this: [TS playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABBATgUwIZTQZQgCzQFsMAeAFQD4AKDAfgC5EMwBPASifMQG8AoRInRQQKJBgDcfAL58+MMNhTAMENIgCiANzSKA8gCMAVmmi8BiKKwAOaJgGcoKBQHMpsvlduIAsqvwKuATEZOQAwgjYAB5QADSI5Nq6UIhoMboAJvaaOvrGplCUiAC85oL2wSSMZYLIkWlQ1eH1MVK1qblQ9k1Jim2I0v0I1fztANoA0ogKCb1QYwBEXmgLALqrIxbtqrAI3UzU0FFcEYoN7CVFWnAwGf2CgxbSiABkNYIA9B+WAdkELC40NkDGh8BgtPAUEwjCBHMwkAolPYCvAkAB3GBQfDw1gAP0QcHyZmWW0QCwAVAtqmAQEQQSh+o9HnwMqYADYYdCIUCQXZIVCYbB+AiBCinaJxWadVLpMBZXiWGx2RCOZxgFwDGgWCqEEhMYUBMBBXWhcUNeKJTqUPicRDXW5STxK3ysM0xEoKsAYIjK1WuAZSZYuuYeniK2xMBY4ACCAE0APoACQ0ABkU3oFgG5F9EICjc4INkFMA0Ch0BlEAYMMiKwgyUHrCg4BDWSh7As+AKsGgDYFqKMVZUMEwB4IIC0oEwu9g8CbSD5XROaOxYqS0J17FP0N3ZyF56w5svVw9jwSwCPSTGE8m03oL+1Pt8AEIAJT0Ew0ADl4uvdD84CALjYmihBIPgzalv6EEoD86gAAY7Ki9hwYgjZwLYKBWIgaLqBALAqmg6hYrhcBlgUbKsNMYAlmRGQfGhLZoBWQbAKRiBwUccGkoIiF7AcRwXMURSjg+GBsqWUCHFAUQAHRej67D3LU0inieTyrtIinZt8aTWGyMAQJiFGoU2jEVnmkGFp225Cv4ooLm6kqHv2FgIPetRXkmqbpu57Q5gA6noL4TDg3HMNASH8dJgnCWFPHiZhUmyfJaBaQ+AyqRl6kyFpQA)

It really looks like a TS issue so I will be reporting it to the TS team later.

This can be fixed by computing the intersection type but I'm slightly worried about the performance implications of this. It would be great to gather pre and post diagnostics for this change. You can see it in action [here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9gWzAV2BAPAQQHxQLxQDeUA2gNJQCWAdlANYQhwBmUmAugFxvntQC+UAGRRk1OtTgB3agG4AUPOZiAxsEpxaKgE4QAhmgDKKgBYQEe9ABVsACj0B+bnuogAlNytF5UKLuDI2rR6CvyKNGjazHoq0ACiAG4Q1MAA8gBGAFYQat6+oJDcAM7A2jQA5qGKBdAAsjEmNBDGZhbW8CkQAB7AADRQVonJwFDdaNQAJkVQQykZ2Wq4BIQ+UEWm5o7cK76+KppoPU4DHYfACrujSSlFx4PX56v8F1Cax-BIqBirvjuXpBQaANZsASAAiGpg9jsY5-f5QGLqTS3bi2NRdTynMZufC4BJwSgTF6XZ4-ATCPL-MEAKjBx2oyAQ6Qg2mJAlW2FCCnkExyABs9LooMpqGoNFpdAYIPVTE12gcxv17sNRj1klMiFAasVShUBHZVutWnpuDLGtRmhs2lYsT0lSDsPIPFB8YTuTUoLUQLaRssoNQ9AgIDqytRygIFB6vSD8JrtVAwYZMABNAD6AAk4gAZLOpMERxQAekLUHKyRZlBU0xozBZugmUHSeiKEAbmgTHrA2jgCUJLKKYPkOn0aDNTVsfyNm22ZP2nR63GHUpam3QXp9djcvTJEAeRUXkqMVss0Yem+3vn4F9e1BnlyTaczOdSd-+xagUjMtA+KDQVGmyAtg2wCNNMADqqQAEpkIYWpwHAZK+Ii4r7lAaLAF0OJ4LgcL-HofIssA6FdAAdAGQZuGyl7XtRTzbvwlFFiW3RgHylaUMAfIgFAXY9n2DZlhaZRVkOh7Sg0crrgqdozGeE6rJor6+A+GbZrmSm7O+EHQYYiEImKyKouiWE4XpSEEdoRHomRgYQIx8JXmSjm0QxChAA)

**Comment by devanshj** [comment]
It does look like an TS issue to me too but here's a [workaround](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABBATgUwIZTQZQgCzQFsMAeAFQD4AKDAfgC5EMwBPASifMQG8AoRInRQQKJBgDcfAL58+MMNhTAMENIgCiANzSKA8gCMAVmmi8BiKKwAOaJgGcoKBQHMpsvlduIAsqvwKuATEZOQAwgjYAB5QADSI5Nq6UIhoMboAJvaaOvrGplCUiAC85oL2wSSMZYLIkWlQ1eH1MVK1qblQ9k1Jim2I0v0I1fztANoA0ogKCb1QYwBEXmgLALqIAD6ICwBUa4wW7VMNmdm7C4ftiHSIYCBEBmgol+1MPMzQ8GDdTNTQUVwIooGuwSkUtHAYBkJAN+oMZFI+BlTAAbDDoRCgSCwBDIdBYNB+AiBChA6JxWadVLpMBZXiWGx2RCOZxgFwDGgWCqEEhMIkBMBBHmhMkNeKJTqUPicRAQqGI5a+ViimIlelgDBEJks1ywzyMpVzNXvZZMBY4ACCAE0APoACQ0ABlHXoFnq+AB6D2IFy6J4wCDZBTAJ7oDKIAwYexocO4pYG6woOBaKFPewXVCYbD8wLUUbMyoYN6XCAtKBMTMEvDC0g+ZVlmjsWKXNCdewV-HYashWusOaN5uCaSDxAIYvtS22h3OvTjq5exAAIQASnoJhoAHLxVu6Sz4OAgFz4RAAd0ISH3OlZ7OTTz36gABqocd8H4hE3BbCgrKf1BAWMyaDqFAhB1Cg6DQCirDTGAIbgTGHofimyLhoqwBwCgiAPv8D4vIgC4AKrWBkBJMAA6noy4TDgeHPl87aIH8UBRKCxRFPmVzMCiTxQExUQAHQalq7D9O0w6XLIQ7NtIIlyAuaTWCiAYwFAUHvkmyExj6frOIGfCVtm-gknWKoUv2eYWGONSCJO9pOi6c7tAuFFUTRnF0QgDF8ax7F4YIGDcd+fGCZqaCyZx4liSO4kyVIQA) for your minimal repro, if it helps!

**Comment by Andarist** [comment]
@devanshj thank you for providing this workaround - it will probably come very helpful in fixing this. Why don't you believe this is a TS issue though? The hover tooltips have this information and providing generics in a different way doesn't result in this problem.

**Comment by devanshj** [comment]
> Why don't you believe this is a TS issue though?

Umm I literally said "It does look like an TS issue to me too" hahaha XD. I agree with you that it indeed is a TS issue for the same reason you stated - the tooltip thing. Am I missing something or just a miscommunication? xD

**Comment by Andarist** [comment]
this is what I get when I'm rushing through GitHub issues between family things 😅 I've misread your comment - thanks for clarifying 👍

**Comment by Andarist** [comment]
With our new types machinery in v5 this should no longer be a problem. The original issue itself is still not fixed in TypeScript though.
