### ISSUE TITLE
Bug with useSelector and "children"

### ISSUE THREAD

**Issue by SimeonC** [statelyai/xstate#2152]
**Description**
Using `useSelector` in combination with an "actor" (invoked service, referenced via state.children), for some reason these two lines of code do not work the same. Even though the custom comparator function is exactly the same as the default. (Please see attached codesandbox as it's kind of hard to describe)

```
const count1 = useSelector(actor, countSelector); // this one never updates
const count2 = useSelector(actor, countSelector, (a, b) => a === b); // this one works (it's the "workaround")
```

**Expected Result**
Both `count1` and `count2` should function identically.

**Actual Result**
`count1` using the default comparator function never updates.

**Reproduction**
https://codesandbox.io/s/xstatereact-bug-reproduction-utt80

**Comment by davidkpiano** [comment]
Added a Replay for this: https://replay.io/view?id=902fa34c-5fa0-4f60-bce9-d96f6db55edf&point=12656223600751063219641806915371361&time=6917.484634404804&hasFrames=true

**Comment by jasonLaster** [comment]
Oh hey @SimeonC! @davidkpiano and I were pairing this morning and found some pretty interesting things in the replay. All of this is in the comments, but passing it along here too:

1.  The fact that the second counter has a custom comparator matters
2. The subscribe call is never called for the default comparator  [link](https://replay.io/view?id=902fa34c-5fa0-4f60-bce9-d96f6db55edf&point=12656223600751063219641806915371361&time=6917.484634404804&hasFrames=true)


It'd be interesting to dig into the subscribe call and see what is going on there

**Comment by SimeonC** [comment]
Hey @jasonLaster! Small world 😀 Xstate and replay.io together is like a superhero crossover event!

I had a look through the replay too and added a comment. My guess is that the useEffect is getting re-called on every render with a non-default comparator forcing the actor to be re-subscribed to. I wonder what would happen if we added the `actor` to the dependencies of the useEffect 🤔 . I think that'd "fix" the issue, but it might cause other issues. Maybe the recreation of `state.children` in the parent machine as outlined in https://github.com/davidkpiano/xstate/issues/1967 is at fault for this?

I've updated my codesandbox to include a couple of variations on referentially stable selector/comparator and non-stable inline functions.

**Comment by Andarist** [comment]
Yep, the problem is that a deferred actor is created at first and it's based on a null actor that has a stub `subscribe` method. So we subscribe to that and we never re-subscribe to the correct actor because we only depend on `selector` and `compare`:
https://github.com/davidkpiano/xstate/blob/62c171d745fe25d04361d8dce553add06464fc96/packages/xstate-react/src/useSelector.ts#L48

The suggestion to also depend on `actor` fixes the problem and would also be required to fix another issue - I think it should be possible to "switch" the input actor during the component's lifetime. I don't have a strong use case for this but I don't see a reason why we should not allow this either.

This will be done at the expense of reexecuting some effects unneccessarily but hopefully this should at least not lead to extra re-renders most of the time. It's a performance optimization that we should handle in v5 though.

This also has some very unfortunate problem that is not easily fixable now in v4 - if you use `useInterpret` and pass around the child actor to `useActor` then we are doomed. The actor change (a resolved actor has a different identity than the deferred actor) won't trigger any rerender and thus the updated actor won't reach the `useActor`

**Comment by davidkpiano** [comment]
Works as expected with latest versions of `xstate` and `@xstate/react`: https://codesandbox.io/s/xstate-react-bug-reproduction-forked-pl35op?file=/src/index.js
