### ISSUE TITLE
[@xstate/react] send function from useActor

### ISSUE THREAD

**Issue by rlaffers** [statelyai/xstate#2412]
**Description**
The `send` function returned from the `useActor` hook has not the same API as the send function returned from `useService`. Since the docs recommend replacing the now deprecated `useService` with `useActor` their accepted arguments should be equivalent.

**Expected Result**
```javascript
const [, send] = useActor(service)
send({ type: 'MY_EVENT', data: 42 }) // works
send('MY_EVENT', { data: 42 }) // should work too, because this format is accepted by
                               // the send function returned from useService
```

**Actual Result**
```javascript
// in the state machine
on: {
  MY_EVENT: {
    actions: (ctx, e) => console.log(e.data)
  }
}

// in a React component
const [, send] = useActor(service)
send({ type: 'MY_EVENT', data: 42 }) // logs "42"
send('MY_EVENT', { data: 42 }) // logs "undefined"

```

**Reproduction**
https://codesandbox.io/s/hungry-sound-gmbny?file=/src/index.js

**Comment by mattpocock** [comment]
@rlaffers Agree that this would be a useful enhancement.

@davidkpiano, should we do this?

**Comment by davidkpiano** [comment]
@mattpocock Yeah, ideally the `send` should be the same function signature as its actor, even if it takes multiple arguments. Will have to do some TypeScript magic to make this work, but it would be an improved DX.

**Comment by mattpocock** [comment]
Alright, I'll take a crack at this

**Comment by Andarist** [comment]
The actor interface doesn't currently allow `send` with multiple arguments:
https://github.com/statelyai/xstate/blob/10944fa6195a3146c7c120d7c3c5c5defeff4e72/packages/xstate-react/src/types.ts#L72

Type incompatibility showcased on the CodeSandbox:
https://codesandbox.io/s/fragrant-wave-ovwvz?file=/src/App.tsx:226-241

IMHO allowing variadic argument length would make things for ourselves unnecessarily problematic - `send` has a clear interface now. It's not like we allow *anything* to be accepted as arguments - we have an expectation that the argument extends `EventObject`. And I find this expectation to be reasonable.

We could change the `send`'s type to be of type `PayloadSender` instead of the simplistic `Sender`:
https://github.com/statelyai/xstate/blob/10944fa6195a3146c7c120d7c3c5c5defeff4e72/packages/xstate-react/src/types.ts#L53-L65

**but** I quite strongly believe (and I know that David probably disagrees with me on that one :wink:) that if the interface requires this kind of type shenanigans to be strictly typed then it's too complicated and a simpler interface should be preferred if it exists (and in this situation it exists). The fact that allowing multiple arguments here is creating a mismatch between `send`'s action parameters and `send`'s method on an actor makes me like this even less.

**Comment by davidkpiano** [comment]
@Andarist Looking at this from a different perspective, this isn't "adding a new way" to send events, given that we can send:

- Event types: `send('SOMETHING')`
- Event objects: `send({ type: 'SOMETHING', payload: 42 })`

And that offering a way to send event types _with payload_ would just be an extension of the 1st way: `send('SOMETHING')` vs. `send('SOMETHING', { with: 'payload' })`. As is evident by this issue, I feel like supporting what has already been supported would make for an improved developer experience.

**Comment by rlaffers** [comment]
@Andarist Yes, there's a mismatch between the `send` action's arguments (one must use the event object when sending some data along) and the `send` method's arguments (more permissive, can combine the event type + payload as the second arg, which makes the DX slightly better when refactoring).

Personally, I would not mind if the permissiveness of the send method was removed altogether to make things consistent.
The issue is that right now there is inconsistency between the send method from useActor vs useService.
So, as I see it, the problem has three solutions:
1. Change the interface of `send` from useActor to `PayloadSender`, to make things consistent, albeit the mismatch between the send method and the send action is kept.
2. Change the interface of `send` from `useService` to `Sender` as well (a breaking change).
3. Keep the status quo, but let's say it explicitly in the docs, that replacing `useService` with `useActor` may require refactoring multiple arguments (if used) into one.

**Comment by IceSentry** [comment]
So, I just hit this bug recently and the typescript type still shows that an optional payload argument is accepted so it was really hard to figure out what was going on. 

I get that it takes time to fix, but adding a single line in the migration guide that mentions this would have saved me and I assume a lot of other people a lot of debugging time.

**Comment by davidkpiano** [comment]
Addressing this in #2501
