### ISSUE TITLE
Services started with State.from() do not run invoked services in their initial states

### ISSUE THREAD

**Issue by mattpocock** [statelyai/xstate#2434]
**Description**
https://www.loom.com/share/da5467b0ff994490a46212d1ad8e35ce

**Reproduction**
https://codesandbox.io/s/wandering-cloud-0o9ds?file=/src/index.js

**Additional context**
XState version 4.23.0

**Comment by JReinhold** [comment]
Furthermore "always" transitions (and possibly other eventless transitions as well) are not triggered either, but they ARE triggered when the actor receives an event, any event, bogus or not.

See repro: https://codesandbox.io/s/amazing-taussig-dcjsv?file=/src/index.js

**Comment by davidkpiano** [comment]
The state that is passed into `service.start(persistedState)` is expected to have all the actions it wants to be executed, because (currently) the service will blindly execute those actions instead of trying to determine what are the right actions it needs to execute.

There's also good reason for this: since there are potentially many ways to reach a state, there can be different actions that should be executed for a state, which is why it's best for the service not to "guess" the actions, to avoid unwanted behavior. 

However, I suppose that there are some actions that are safe to assume: entry actions. I'm just not sure how much of a breaking change it would be if we introduce those actions... and there's also the use-case of wanting to restore the state but not wanting any actions executed, which that change would make impossible.

**Comment by JReinhold** [comment]
But when I read the [docs on State.from and State.inert](https://xstate.js.org/api/classes/state.html#from) it reads to me like it is in those calls that we decide if any actions or services on the state should be executed or not?

**Comment by mattpocock** [comment]
@JReinhold yeah that does make sense. Ideally, you'd use `State.inert` when you want an actor without entry actions.

@davidkpiano It does concern me that we don't run invoked services. Are you sure it's working as intended?

**Comment by Andarist** [comment]
> Furthermore "always" transitions (and possibly other eventless transitions as well) are not triggered either, but they ARE triggered when the actor receives an event, any event, bogus or not.

Always transitions are triggered after receiving an event (whatever event, matched or not). Since if you `start` with a persisted state those transitions were already triggered - just before you could persist that state, so reselecting them again *without* a new event sounds potentially incorrect.

> @davidkpiano It does concern me that we don't run invoked services. Are you sure it's working as intended?

I think that Ideally, the persisted state would have children persisted states on it and we would "rehydrate" the children based on this information. Internally this would probably roughly translate to `child.start(childState)` so the `child` could "start" taking this information into account. A machine child would somewhat easily rehydrate itself, whereas, for example, a promise child would either just store the final result if its `childState` was "fulfilled" (or rejected) or it would be executed again if the `childState` was "pending".

Those are, of course, just my raw thoughts.

**Comment by mcuppi** [comment]
I've found that you can use [`getInitialState()`](https://xstate.js.org/api/interfaces/statemachine.html#getinitialstate) to start a service at a specific state node and run its invoked services. Resolving a state in this manner will also cause the interpreter to run the node's `entry` actions, as well as root level invocations.

_Please note, I haven't extensively tested or researched all of the consequences of using this method yet_.

Here is a modified version of the original sandbox with everything working as expected: https://codesandbox.io/s/elated-hodgkin-ev9bu?file=/src/index.js

**Comment by telmaantunes** [comment]
Get `getInitialState()` worked for me too, but it sucks that is not mentioned on the xstate guides

```
startService() {
  this.service
     .onTransition((state) => {
        this.persistState(state);
        // ...
     })
    .start(this.restoreState());
}

restoreState() {
  const stateDefinition = // get it from wherever you persisted it

  /**
  * use getInitialState instead of recommended State.create
  * so that invoke and transition actions are ran again
  *
  * recommended way: State.create(stateDefinition)
  */
  return stateDefinition
    ? this.machine.getInitialState(stateDefinition.value, stateDefinition.context)
    : undefined;
}
```

**Comment by nikpundik** [comment]
Great to know about `getInitialState()` but unfortunately is not working with parallel states. Forcing an initial state on a parallel state will make the specified state to invoke its service/entry actions, but not the others of course.

Example: https://codesandbox.io/s/mystifying-bush-ogcmg2
