### ISSUE TITLE
Version 4.23.0 breaks typing of "$" prefixed service inside svelte component

### ISSUE THREAD

**Issue by DavKato** [statelyai/xstate#2533]
**Given this**
```ts
const machine = model.createMachine(...)
const service = interpret(machine).start();
```

**Until 4.22**
```ts
const { someData } = $service.context // This returns the correct type
```

**From 4.23.0**
```ts
service.subscribe((state) => {
  state.context // This still returns a correct type
})
const { someData } = $service.context // $service becomes any
```

**Comment by annaghi** [comment]
`service` is not a reactive store, you cannot use the `$` sign on it. `state` is the store:

```js
const { someData } = $state.context;
```

https://github.com/statelyai/xstate/blob/5da8724bb6c4dada5d6e8cc61e36c7e2c771838b/packages/xstate-svelte/src/index.ts#L62-L80

**Comment by DavKato** [comment]
@annaghi Thank you for a quick response!
Actually I'm not refering to xstate-svelte, I'm just using a plain xstate.

Service here is just a xstate service like this.

```ts
const machine = model.createMachine(...)
const service = interpret(machine).start();
```

Service is subscribable and we still can access it's state with "$" syntax, only the typings is broken with 4.23.0.

**Comment by annaghi** [comment]
@DavKato Oh, you are right! I was not aware of that the `service.subscribe` is compatible with the Svelte store contract. Sorry for my silly comment. :)

**Comment by DavKato** [comment]
@annaghi No worries! I updated the issue to make the point clearer.

**Comment by Andarist** [comment]
@DavKato could you prepare a runnable repro case? It would make it easier for us to jump straight into playing with this problem

**Comment by DavKato** [comment]
I couldn't configure codesandbox, so here's a github repo.
https://github.com/DavKato/xstate-typefail

**Comment by chanced** [comment]
I have a slightly different take on the svelte implementation here: https://github.com/chanced/xstate-svelte

I just spiked it out last night so it doesn't have tests but you can find a quick example of the usage here: https://github.com/chanced/xstate-svelte/blob/main/src/routes/index.svelte

If its something that you guys are interested in, I can work on a pull request with tests and such. Otherwise, I'll get around to testing and publishing it as a package. I'll be sure to annotate credit to the original as it is largely a fork.

**Comment by DavKato** [comment]
I found out that reverting this commit solves this issue.
https://github.com/statelyai/xstate/pull/2371/files

**Comment by davidkpiano** [comment]
> I found out that reverting this commit solves this issue.
> https://github.com/statelyai/xstate/pull/2371/files

Reverting this will likely break other things, though, no?

**Comment by DavKato** [comment]
> Reverting this will likely break other things, though, no?
Yes :|

**Comment by DavKato** [comment]
I think the tag `@xstate/svelte` is inaccurate here, this issue is caused by the typing change in the `core` and there is nothing to do with `@xstate/svelte`.

But I'd say severity of this issue has dropped significantly by the introduction of `useSelector` to `@xstate/svelte`.
I'm pretty positive that one should always prefer using `useSelector` instead of direct access with `$`.

**Comment by Bickio** [comment]
I was grappling with this issue today for longer than I'd like to admit (compounded by this one https://github.com/tomblachut/svelte-intellij/issues/266).

The issue here is that the `subscribe` method returns an `Subscription` object, instead of a plain `() => void` function, meaning svelte doesn't consider it a `Readable`.

I think the best solution (assuming there are strong reasons for returning a `Subscription`) is to update the docs and call it spec :)

**Comment by davidkpiano** [comment]
> I was grappling with this issue today for longer than I'd like to admit (compounded by this one [tomblachut/svelte-intellij#266](https://github.com/tomblachut/svelte-intellij/issues/266)).
> 
> The issue here is that the `subscribe` method returns an `Subscription` object, instead of a plain `() => void` function, meaning svelte doesn't consider it a `Readable`.
> 
> I think the best solution (assuming there are strong reasons for returning a `Subscription`) is to update the docs and call it spec :)

What version of Svelte are you using? I see in the Svelte docs that returning an object with `.unsubscribe` is allowed:

> **For interoperability with RxJS Observables, the .subscribe method is also allowed to return an object with an `.unsubscribe` method, rather than return the unsubscription function directly.** Note however that unless `.subscribe` synchronously calls the subscription (which is not required by the Observable spec), Svelte will see the value of the store as undefined until it does.
> https://svelte.dev/docs#component-format-script-4-prefix-stores-with-$-to-access-their-values-store-contract

**Comment by DavKato** [comment]
I believe the problem here is not subscribe method returning the Subscription, but the call signature of `subscribe` method.

> I found out that reverting this commit solves this issue.
> https://github.com/statelyai/xstate/pull/2371/files

This simple reorder of overload signature solve the issue for rxjs, introduced an issue for svelte.
An interesting fact I learnt from [@Andarist 's comment on this PR](https://github.com/statelyai/xstate/pull/2371) says:
> This obviously is a very weird change but I believe that it's related to how TS, at times, casts overloaded functions to their  > last overload signature. 

The signature that svelte expects for subscribe method is;
```ts
subscribe(run: (value: T) => void)`
```
[source](https://github.com/sveltejs/svelte/blob/d487254beb9a42ed550cccc103d2017856ee0cbe/src/runtime/store/index.ts)

But ts casts the last defined signature which is;
```ts
subscribe(observer: {
  next: (value: T) => void;
  error: (err: any) => void;
  complete: () => void;
})
```

**Comment by davidkpiano** [comment]
@DavKato Would reordering the overload signatures fix the issue for both RxJS and Svelte?

**Comment by Andarist** [comment]
> @DavKato Would reordering the overload signatures fix the issue for both RxJS and Svelte?

That's unlikely because those overloads have been explicitly reordered to fix the RxJS problem so reordering them again would just flip the situation - break compatibility with RxJS but improve it with Svelte.

@DavKato do you happen to know where Svelte tries to compute the type of the $-prefixed variables? Just looking into the `.svelte` file opened with VScode doesn't give me that much insight because this is handled through their magic and their language server.

**Comment by chanced** [comment]
This can be rectified in the svelte-xstate package. See https://github.com/chanced/xstate-svelte/blob/b68fde50eeb149ef4b4d02c96c65adb973bf9a15/src/lib/bootable.ts#L35-L126

It has been awhile since I touched xstate and I can't recall where I left off with that spike. However, I'm pretty sure it was working. Ignore the silly name (bootable). I was planning on changing it.

**Comment by Andarist** [comment]
The problem here is slightly different though because it's not about using a machine within a component and tieing the lifetime of this machine to the component (this is what `@xstate/svelte` is about) but rather about using our interpreter etc as readable. In this case, the interpreter can be instantiated outside of Svelte and just imported to the component.

We could, of course, provide some kind of a `useActor` or something that would "convert" our structures to what Svelte can understand.

There is a chance though that maybe we could make `$service` to work again and this has to be explored. I'm not yet entirely sure if I'm looking at the right thing but I think the type of the subscribable gets extracted here:
https://github.com/sveltejs/language-tools/blob/42f273ec087c2e6966e23bcce08aee2fc5e1dcda/packages/svelte2tsx/svelte-shims.d.ts#L161-L162

With this signature I'm able to replicate the problem:
- [with 4.22.0](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzsAdjAplMV3wL5wBmUEIcARAB4DOMAhhgPQA2wARo6hljt+QNxxGjODACeYdNQBccACwA6AExKFABgBQoSLERwAxjgboAshAAm6ZnALFSFGvSasOIC1YFCR4yTPnLVTQ19CBRaODdLawBeAyMMMyiACg04RFS05HNZcgBNAHlyABoMvBK0hAy09AA3dDQ-SszMlHRKGFkkwmgAJXQ6Zlk2CAhmfpQASjhogD44JKRuqD6BmwnyzLLSjQn+DWDQ8JA6fQALVHRpiPdmBUN+hJPz1oWM4GyKDFpijJC0No61yiClQwBgwAGAGFQhh2htaMZGlU4KF0LIms0USh0cjmq12jkYAB3CA-TE2DZpLbNYkQHHk0L08lwfGA8iosmY6mbDZbPC7fY+S4AZTqzAwwpg0HQAB4ACpzWIY6gAVzY1EM7DR8ygKux8xqAxV2rlU1mcDoKDERWQKENrHMxgA-LJLWIzXM3Xs8HsNJZ9Mw6DgiHr9ODQnAAPqR6hijAwaiRgCMMalOEjAHNcPKrm6ZklaNLZKKrBK07KFRNZHK9v7A8HCKHwygozG47hEynC+mszAZRlJdK4AD6uZqHAS+L0IOcDK83AAD5wPWWQgXcyLlkq5jMDT57vamfoKsT8vD9qj8eTsvSmWoQiYOAKuBOp9wYvl31-cLUTA1YD6JcsRcJg2C4EkxxnBcEwKAisBJAKBxhPAkY4OOsTRrGpYdsmqbSpm4G-lA-6AQKwiZAAek6GhAA)
- [with 4.23.0](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzsAdjAplMV3wL5wBmUEIcARAB4DOMAhhgPQA2wARo6hljt+QNxxGjODACeYdNQBccACwA6AEwBmBQAYAUKEixEcAMY4G6ALIQAJumZwCxUhRr0mrDiEvWBQkeMkz5ympamgYQKLRw7lY2ALyGxhjm0QAUmnCIaenIFrLkAJoA8uQANJl4pekImenoAG7oaP5VWVko6JQwssmE0ABK6HTMsmwQEMwDKACUcDEAfHDJSD1Q-YO2kxVZ5WWak-yaIWERIHQGABao6DORHswKRgOJpxdti5nAORQYtCWZoWjtTo3aIKVDAGDAQYAYTCGA6m1oJia1TgYXQsmaLVRKAxKJabQ6uRgAHcIL8sbZNulti0SRBcRSwgyKXACUDyGjyViaVtNts8HsDr4rgBlerMDAimDQdAAHgAKvM4pjqABXNjUIzsdELKCqnELWqDVU6+XTOZwOgoMTFZAoI2sCwmAD8sitYnN83d+zw+00VgMzDoOCI+oMELCcAA+lHqOKMDBqFGAIyx6U4KMAc1wCuu7tmyVoMtkYuskvTcsVk1k8v2AaDIcIYYjKGjsfjuCTqaLGezMFlmSlMrggIaFmocFLEvQQ5wsvzcAAPnB9VZCJcLEvWarmMxNAWezrZ+hq5OKyOOmOJ1PyzLZahCJg4Iq4M7n3ASxW-f8ItRMLVgAMK44i4TBsFwZITnOS5JgURFYGSQVDnCeAoxwCc4hjOMy07FM0xlLMIL-KAAKAwVhCyAA9Z1NCAA)

**Comment by chanced** [comment]
Your interpreter being service, yea?

```ts
	const service = readable(interpreter, (set) => {
		set(interpreter.start(rehydrateState));
		return () => {
			rehydrateState = interpreter.state;
			interpreter.stop();
		};
	});
```

**Comment by chanced** [comment]
The other issue with `@xstate/svelte` is how the interpreter is stopped. The codebase I linked resolves that as well.

**Comment by Andarist** [comment]
The code that you have pasted here is about a different problem though - as mentioned, this issue is about treating interpreters as readables (at the TS level) and not about converting/wrapping machines/interpreters into readables. Your code looks OK - it's just solving a different problem than outlined here.

> The other issue with @xstate/svelte is how the interpreter is stopped. The codebase I linked resolves that as well.

Could you create a new issue about this? Mentioning expected & actual results for a given input code would also be very helpful in understanding what we do wrong in `@xstate/svelte`

**Comment by chanced** [comment]
That's my fault. Sorry about that.

**Comment by Andarist** [comment]
FYI - I might have figured out a solution for this problem: https://github.com/statelyai/xstate/pull/3063 . Note that if we'd be dealing with 2 libraries using different signatures for a **single** method (as if Rx part of the puzzle wouldn't rely on a separate `Symbol.observable` method) this wouldn't be quite possible to solve. At least not in such a way.
