### ISSUE TITLE
Pure actions are called twice when invoking machines

### ISSUE THREAD

**Issue by KevinGulj** [statelyai/xstate#2566]
Hello 👋 

**Description**
I have been using pure actions, and after moving to Models & invoking machines, some pure actions are called twice.
Also the child machine is seemingly invoked twice.

**Expected Result**
Both should happen only once?

**Actual Result**
Getting multiple calls for pure actions & invoke

**Reproduction**
As you can see in the console, pure actions are being called twice, also the invoking is happening twice.
https://codesandbox.io/s/sharp-gould-j6nd8

**Additional context**
xstate 4.23.1
@xstate/react 1.5.1

**Comment by davidkpiano** [comment]
This is working as intended. Actions returned from a `pure(...)` action creator may contain `assign(...)` actions, which need to be evaluated to determine the initial state. Since services aren't started immediately in React (limitation: effects are run _after_ the initial render), there are two times the initial state is determined:

1. When the component is instantiated
2. When the service is started

The initial state of these two can differ, especially when spawning/invoking actors in the initial state, which is why there needs to be a double evaluation.

In general, `pure(...)` actions should remain pure. Don't execute any side-effects in them.
