### ISSUE TITLE
[@xstate/svelte] Missing ESM exports

### ISSUE THREAD

**Issue by f-elix** [statelyai/xstate#2642]
**Description**
Right now, the distributed package of @xstate/svelte only exports CJS and this caused some problem after an update in SvelteKit (https://github.com/sveltejs/kit/issues/2418). 

**Expected Result**
In any case, Xstate core exports both CJS and ESM. Is there any reason why it isn't the same with @xstate/svelte? If there isn't any, I think it should have an ESM export.

**Comment by davidkpiano** [comment]
cc. @farskid @Andarist

**Comment by schibrikov** [comment]
I also have a problem there. I'm using SvelteKit and xstate with @xstate/svelte and it causes problems when building for e.g. cloudflare where SvelteKit tries to bundle the application with esbuild.
I guess the problem is svelte bindings are compiled for commonjs which results in something like this inside:
```var xstate_1 = require("xstate");```
After rollup processes the application it's becoming this:
```import require$$1, { createMachine } from "xstate";``` (because the input was commonjs like)
So when esbuild comes into play it's looking for **default** export in xstate which is not present.

I'll try looking into it and maybe make a PR with ESM target.
