### ISSUE TITLE
EventFrom marks optional properties as required

### ISSUE THREAD

**Issue by CodingDive** [statelyai/xstate#2777]
**Description**
When extracting event types from a model blueprint with `EventFrom`, optional properties of the event will be treated just like required properties.

**Expected Result**
The type of optional properties should be preserved

**Actual Result**
Optional properties are marked as required

**Reproduction**
See PR with failing test or codesandbox [here](https://codesandbox.io/s/patient-hooks-1y04o?file=/src/index.ts)

**Comment by janovekj** [comment]
I have only briefly looked into this, but so far it doesn't look like this is was introduced by #2743.

Weirdly enough, this seems to work when I'm testing it right inside [types.ts](https://github.com/statelyai/xstate/blob/main/packages/core/src/types.ts)
<img width="713" alt="bilde" src="https://user-images.githubusercontent.com/10179626/139596856-9c153c47-90d1-4cfb-b5b3-d7ad38dce490.png">

**Comment by Andarist** [comment]
@CodingDive there is a difference between an optional property and a property with an undefined value. Since we are using the return type to create final event types, this is somewhat expected (although inconvenient). See a slightly modified variant of your code to see how it can behave differently:
[TS playground](https://www.typescriptlang.org/play?strict=false&strictNullChecks=false#code/JYWwDg9gTgLgBAbzgUQG4FMB2MBiUIhwC+cAZvoQEQAeAzjAIYzqUDcAUKJLInAMZR0TdAFkIAE3QAbYmQpwa9YQHopwAEbKQE6W3bs+ETPTjbJMgLz9BwseYAU7OL0MBXbAC44AZmIAaJ0RA53QMbFovBGDnOABJADkAYS97AEo4CwA+OHsEIlSAmJjkADVkeIAVAH0AdViKgAkqgHkABQrY5viAQQAZKtaAJTaUiDAYYCMGKW6oAHMAfi96KGBMObgAHzh3SVI19HF0rKCiouBSHLGJqZn59Kizs8EYVyhMXmvJzGnZjaJokUAU9nC83h88oDiNFgdDUhx2DAAJ5gdAoMLwKxoLC4CgAHmRqIglzM0gAdAIhMwRAw+AALA6ZDhAA)

I'm not saying that this is how you should write the code - I'm merely showcasing this so you can better understand how this works. If we take a closer look you have created a factory function that takes an optional **parameter** but the returned object has **always** that property on it.

I doubt there is anything we can do about this - we could take into account the optionality of the parameters and try to "transfer" that to the created event types. However, this would make things way more complicated and would also make the other use case not possible to express (required prop with optional value). 

@janovekj I believe that you were experimenting without `strictNullChecks: true`.

**Comment by CodingDive** [comment]
@Andarist interesting! Thank you so much for for sharing.

The syntax you described actually seems to fix the issue I've been having as the event type now rightfully shows the property can be optional/undefined too. 

```TypeScript
EVENT_WITH_OPTIONAL_PROP: (optionalArg?: string | undefined) => {
  if (optionalArg) {
    return { optionalArg }
  }
  return {}
}
```

Feel free to close the issue if this is the syntax we should be using going forward!
