### ISSUE TITLE
`interpreter.state.can()` does not work with `createModel`

### ISSUE THREAD

**Issue by huan** [statelyai/xstate#2859]
**Description**

With `createModel()`, the typing of `interpreter.state.can()` seems not right.

**Expected Result**

`state.can()` should accept the EVENT names from `createModel()`

**Actual Result**

> Argument of type 'string' is not assignable to parameter of type '{ text: string; type: "TEXT"; }'.ts(2345)

**Reproduction**

https://codesandbox.io/s/tender-https-vm798?file=/src/index.ts

**Additional context**

I have tried:

```ts
interpreter.state.can('TEXT')
interpreter.state.can(model.events.TEXT)
```

But without any luck.

```ts
type T = Parameters<typeof interpreter.state.can>[0]
// type T = {
//     text: string;
//     type: "TEXT";
// }
```

**Comment by davidkpiano** [comment]
This is behaving as expected. `state.can(...)` accepts an event type of _simple events_, which are events that have no payloads; otherwise, it requires a full event.

A simple work-around:

```js
interpreter.state.can({ type: 'TEXT', value: '' }) // dummy value
```

However, it makes sense for a use-case to be "I want to know if this event with any parameter will cause a transition to be selected". We have some changes (#2850) coming in that might permit this.

cc. @Andarist What do you think?

**Comment by huan** [comment]
Thank you very much for the quick reply and the clear explanation!

So it seems that the below workaroun works:

```ts
interpreter.state.can(model.events.TEXT(''));
```

> "I want to know if this event with any parameter will cause a transition to be selected"

And the above is what exactly I want, it would be great if we can have a compatible `can('EVENT')` to achieve that!

**Comment by davidkpiano** [comment]
This has since been fixed.

**Comment by huan** [comment]
Fantastic, thank you very much for the fix!
