### ISSUE TITLE
CreateModel causes SvelteKit to fail during build

### ISSUE THREAD

**Issue by heinschulie** [statelyai/xstate#2893]
**Description**
Hi there. Firstly, thanks for Xstate. It's made my life considerably easier. 

For context, I am encountering this issue using SvelteKit. When creating machines using "createMachine" there is (obviously) no problem and all works well. 

Expecting that this may be beneficial moving forward, I have recently started refactoring these machines using the "createModel" pattern. Although everything runs smoothly in dev, what I have discovered after a few days work is that "createModel" causes an error to be thrown during a prod build.   

If this is some simple config thing I have overlooked I apologise. Hopefully it's something easy to address as it would be great to continue down this refactoring path seeing as you the docs mention that it "_is meant to improve the developer experience_". 

**Expected Result**
That no build error is thrown. 

**Actual Result**
This error is thrown during the build process: 

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '... /node_modules/xstate/lib/model' imported from .../.svelte-kit/output/server/chunks/index-30886392.js Did you mean to import xstate/lib/model.js?

**Reproduction**
I created this tiny repo that demonstrates the issue well. You can simply comment in/out the references to the machines being created in the two different ways. 
 
https://github.com/heinschulie/carbon

**Additional context**
"xstate": "^4.26.1"

**Comment by Andarist** [comment]
Your `home.model.ts` is being executed within node itself and since you have set `"type": "module"` in your package.json this gets loaded using the new node's ESM loader semantics. Therefore, to make it work you need to apply this diff:
```diff
diff --git a/src/lib/machines/home.model.ts b/src/lib/machines/home.model.ts
index 1745f74..b7c3619 100644
--- a/src/lib/machines/home.model.ts
+++ b/src/lib/machines/home.model.ts
@@ -1,5 +1,5 @@
 import type { ContextFrom, EventFrom } from 'xstate';
-import { createModel } from 'xstate/lib/model';
+import { createModel } from 'xstate/lib/model.js';
 
 export const homeModel = createModel(
     {
```

We are going to improve the story around this but XState v4 has been released **before** node's ESM support. We couldn't anticipate how it would work and unfortunately, it has been shipped in a way that is not compatible with the existing ecosystem. If we want to make it work - we need to adapt to it but this can only be done in the next major version of XState as changing things like this is very delicate and this could be a breaking change for the existing users.

**Comment by heinschulie** [comment]
@Andarist - thanks for the super quick response. Especially at this time of year. All works well now. Really looking forward to v5.
