### ISSUE TITLE
Cannot use raise action in model-based machine

### ISSUE THREAD

**Issue by wKovacs64** [statelyai/xstate#2897]
**Description**

TypeScript gets mad when you try to use the `raise` action inside a model-based machine definition.

**Expected Result**

I would expect it to work as it does with a machine not created from a model.

**Actual Result**

```
Type '{ STEP: { target: string; }; RAISE: { target: string; actions: (RaiseAction<EventObject> | SendAction<unknown, AnyEventObject, EventObject>)[]; }; }' is not assignable to type 'TransitionsConfig<{}, UnionFromCreatorsReturnTypes<FinalEventCreators<{ STEP: () => {}; RAISE: () => {}; NEXT: () => {}; RESET: () => {}; TOGGLE: () => {}; }>>> | undefined'.
  Types of property 'RAISE' are incompatible.
    Type '{ target: string; actions: (RaiseAction<EventObject> | SendAction<unknown, AnyEventObject, EventObject>)[]; }' is not assignable to type 'TransitionConfigOrTarget<{}, { type: "RAISE"; }>'.
      Types of property 'actions' are incompatible.
        Type '(RaiseAction<EventObject> | SendAction<unknown, AnyEventObject, EventObject>)[]' is not assignable to type 'Actions<{}, { type: "RAISE"; }> | undefined'.
          Type '(RaiseAction<EventObject> | SendAction<unknown, AnyEventObject, EventObject>)[]' is not assignable to type 'Action<{}, { type: "RAISE"; }>[]'.
            Type 'RaiseAction<EventObject> | SendAction<unknown, AnyEventObject, EventObject>' is not assignable to type 'Action<{}, { type: "RAISE"; }>'.
              Type 'SendAction<unknown, AnyEventObject, EventObject>' is not assignable to type 'Action<{}, { type: "RAISE"; }>'.
                Type 'SendAction<unknown, AnyEventObject, EventObject>' is not assignable to type 'string'.(2322)
```

**Reproduction**

https://stately.ai/viz/293fb8f2-2ede-4e1f-965f-9e1288097cb3

**Additional context**

I created this minimal reproduction because it wasn't working in my real app. In the real app, it's more than a TS error though - it doesn't seem to raise the event at all. I'm assuming there must be more to the story in the real app though, as the reproduction here _does_ actually work, it just makes TS mad.

**Comment by Andarist** [comment]
I'm not yet sure what happens here, but this is what I've gathered:
1. the problem goes away if we remove [the `exec` property from the `ActionObject` type](https://github.com/statelyai/xstate/blob/df5ffce14908d0aa8056a56001039dfd260be1a4/packages/core/src/types.ts#L46)
2. the ['bivarianceHack'](https://github.com/statelyai/xstate/blob/28ef36941b7a3be859770ecf2ce623c28c11ec3a/packages/core/src/types.ts#L98-L108) doesn't help this case
3. replacing the `exec` with phantom types like this `__TContext: TContext; __TEvent: TEvent;` doesn't help either
4. I couldn't repro the assignability problem with simple variance/contravariance checks like the ones [here](https://www.typescriptlang.org/play?#code/PTAEFMCdIe00CWA7UANAygFwIafALgCgRQAVATwAdxQBydcJAEwEEBjTBGJAHgFckAayQwA7kgA0oFknIBRAG6NMAeQBGAK3AcpAb1CYqBUACJSKgOIWAMnJMBuUAF8AfLUQBnUCMyhsHjwQAcyRsNQAbGkwYAyM6dk5uHl0nPVjqfFMAJRYASXQ7R1daADpCYjBROEEPQjZuD18FbEgEbCQ2YwSuXhS0wwy6HPy5d1dQAF5QFL8vBmZupMJQUAFhMUll6VlFZXUtHS39AeNacytbMcIXe3KSKsgauobfeqRMSGxm1vbMTIAKbCZRa9VLTdKnYYFMYuACUkxcoAUMAQTEm0ycs1A-y2QNA81YHB6-CEInEUhk8iU7322kw-SMmTOlhso2cLkI8ImiORqNuFVAHhiogAFuREK92hBoHBEChMCKaAAzBCQRqgSjhbCdAD8QA)

**Comment by Andarist** [comment]
Ok, I think I've cracked this - but I didn't try to fix this yet. I **think** that the error is because transition actions are narrowed down to accepting a particular event type. In this example the accepted event type would be `RAISE`:
<img width="606" alt="Screenshot 2021-12-28 at 13 45 35" src="https://user-images.githubusercontent.com/9800850/147567786-b4ffc414-d1b0-492c-a419-d01cc87f2891.png">

The problem is that the "accepted" event type is only used to resolve expressions but send and raise can "create" any events that are accepted by the whole machine (and not just those that are accepted by expressions in the given transition).

Our `Actions` type (nor `BaseActions` that is used for typing `exit` and `entry` actions) doesn't understand the distinction between both - they are just accepting a single `TEvent` generic. It seems like we should accept two in those places - `TExpressionEvent` & `TEvent`

I also think that both `Actions` and `BaseActions` should be unified. I don't see why one would be used for `exit`/`entry` and the other one is only used for transition `actions`.

**Comment by davidkpiano** [comment]
I'm working on this here: https://github.com/statelyai/xstate/pull/2690

That PR will improve action types so that they also accept a `TSpecificEvent` generic, since that is different from `TEvent` for transitions.
