### ISSUE TITLE
Testing `onError` transition using Jest surfaces unexpected console.error 

### ISSUE THREAD

**Issue by mindy** [statelyai/xstate#2919]
## Description
When trying to test the `onError` transition logic using Jest, it surfaced a console.error stating that the `onError` handler was missing, even though it was defined in the machine. However, adding a `target` property fixes the error: 

```
onError: {
  // target: "fetchComplete" < adding a target fixes error
  actions: escalate((_, event) => event)
}
``` 

The error only appears during testing and does not appear when interacting with the machine in the browser. 

## Expected Result
Should not see any console errors when testing the `onError` transition without a `target` property. 

## Actual Result
```
  console.error
    Missing onError handler for invocation 'apiRequest', error was 'removal failed'.

      at console.error (node_modules/@testing-library/react/dist/act-compat.js:52:34)
      at Object.reportUnhandledExceptionOnInvocation (node_modules/xstate/lib/utils.js:535:15)
      at node_modules/xstate/lib/interpreter.js:1016:17
```

## Reproduction
https://codesandbox.io/s/festive-star-juruk?file=/src/index.test.ts

_Note: There's an [issue](https://github.com/codesandbox/codesandbox-client/issues/513) with using `jest.mock` in Codesandbox, so running the tests in browser doesn't work._ 

## Additional context
- Discord link: https://discord.com/channels/795785288994652170/809564635614150686/928385438652186674 
- Relevant packages and versions: 
```
"xstate": "^4.23.1",
 "@xstate/react": "^1.5.1",
"jest": "^26.0.0",
"jest-dom": "^3.5.0",
```

**Comment by Andarist** [comment]
Thank your for the report and the repro case. From the description it looks like a bug but given that escalate is also used here - maybe there is some parent & child relationship that makes a difference here. Gonna examine this carefully asap

**Comment by Andarist** [comment]
This is almost the same problem as the one described [here](https://github.com/statelyai/xstate/issues/2920#issuecomment-1006778813). You have mocked `escalate` and when that function is called it returns `undefined` but it should return something resembling an action (like a function).

The logic responsible for throwing the error that you are observing is based on this:
https://github.com/statelyai/xstate/blob/9f9184a534c9f49e9e76a75d8113aa4d0c812f2d/packages/core/src/StateNode.ts#L1797-L1807
And since your `actions: escalate()` is really an equivalent to `actions: undefined` then the normalized `transitions.actions` is just an empty array and as such your targetless `onError` is not treated as a transition that does something meaningful.

**Comment by Andarist** [comment]
Gonna close this for now as there is nothing actionable for us here but if you believe that the issue/question has not yet been addressed in full, let us know so we can provide more information.

**Comment by mindy** [comment]
Apologies for my late reply @Andarist -- I appreciate your explanation (that makes total sense!) and the time and effort you took to look into this. Thank you!
