### ISSUE TITLE
machine.transition is not pure (delete history.history)

### ISSUE THREAD

**Issue by Isokaeder** [statelyai/xstate#2945]
**Description**
By calling `machine.transition` on a predefined state, that state's history is mutated. This is in contradiction to the doc's claim that [machine.transition is a pure function](https://xstate.js.org/docs/guides/interpretation.html#custom-interpreters).

**Expected Result**
State is not mutated by being used as a parameter in `machine.transition`

**Actual Result**
`state.history` is deleted

**Reproduction**

- [CodeSandbox template (TypeScript)](https://codesandbox.io/s/hungry-voice-9c9ge?file=/src/index.ts)

**Additional context**

Cause is likely that here `currentState` is passed without deep cloning
https://github.com/statelyai/xstate/blob/56842cb39110923afe70280dde744bea4f81d6dd/packages/core/src/StateNode.ts#L1260-L1262

here `history` is deleted from both `nextState.history` and `currentState`
https://github.com/statelyai/xstate/blob/56842cb39110923afe70280dde744bea4f81d6dd/packages/core/src/StateNode.ts#L1284-L1286

**Workaround**
```ts
import { cloneDeep } from 'lodash'

const nextState = machine.transition(cloneDeep(state.currentState), event)
```

**Comment by Andarist** [comment]
We agree with this and that's one of the reasons why `state.history` has been removed on the `next` branch: https://github.com/statelyai/xstate/pull/2882

**Comment by davidkpiano** [comment]
This is fixed in v5 (like @Andarist said) and a wontfix for v4 since it would be a breaking change - _not_ deleting `history.history` would cause a memory leak, as previously reported (accidental blockchain).

**Comment by FlorianWendelborn** [comment]
> We agree with this and that's one of the reasons why state.history has been removed on the next branch: #2882
> — @Andarist

That’s good enough for our use-case as we don’t expect to be relying on history at all. Is `next` already reliable/stable? If no, do you have a rough, educated guess-based estimate when it could be approximately ready?

> This is fixed in v5 (like @Andarist said) and a wontfix for v4 since it would be a breaking change - not deleting history.history would cause a memory leak, as previously reported (accidental blockchain).
> — @davidkpiano

I think there’s a misunderstanding here. @HansAuger and I aren’t suggesting that `history.history` should not be deleted. The issue here is that `oldState.history` gets accidentally deleted as well since `newState.history` is initialized using `oldState.history` implicitly.

The fix for that would be changing https://github.com/statelyai/xstate/blob/56842cb39110923afe70280dde744bea4f81d6dd/packages/core/src/StateNode.ts#L1260-L1262 to apply a `cloneDeep` on `history`. This will prevent `newState` to have infinitely-deep history while also **not mutating `oldState`**.

This is presumably how the current API is supposed to work already, and unless the user stores all old states themselves (e.g. in an array), the garbage collector will delete the old history entries when it runs.

The "accidental blockchain" problem only happens if `newState.history.history` is not deleted. Not deleting `oldState.history` shouldn’t cause a memory leak here and IMO is just a bugfix to make the function actually pure as it claims in the docs.

---

If this suggested solution is also not feasible then it would be great if the docs could reflect that `transition` is **not** a pure function, as they currently explicitly claim that it is a pure function.

**Comment by davidkpiano** [comment]
It is now pure in `xstate@alpha`, which does not maintain state history.

**Comment by FlorianWendelborn** [comment]
Thanks a lot @davidkpiano
