### ISSUE TITLE
Bug: Schemata + Typegen break string literals, event suggestions, and `ActorRef` assignments

### ISSUE THREAD

**Issue by christoph-fricke** [statelyai/xstate#3028]
### Description

I noticed a few problem with schemata + typegen:

1. String literals unions (e.g. `"working" | "not-working"`) used in context are broadened to string, breaking selectors and other potential code that requires the string literal union.
2. Since 4.29 the result of spawning a machine is no longer assignable to an actor ref created with `ActorRefFrom`, which makes it nearly impossible to type the spawned machine for passing it around.
3. While preparing the code sandbox, I noticed that VS Code does not infer event types in the machine definition when schemata are used.

### Expected result

1. String literals unions should be typed as string literal unions and not `string`.
2. Spawned machines are assignable to their corresponding `ActorRef`.
3. VS Code should suggest event types in `<state>.on` like it does when events are specified through the generic.

### Actual result

1. Instead of preserving a literal union, the type is broadened to `string`.
2. A nasty TypeScript error appears.
3. VS Code only suggests `""` and `"*"`, not the actual event types.

### Reproduction

https://codesandbox.io/s/floral-bush-yxn10?file=/src/index.ts

### Additional context

In the sandbox, schemas are disabled by default and can be enabled by removing the comments (`createMachine` generics have to be removed as well). 

XState Version: 4.29.0

**Comment by jonnyirwin** [comment]
I started changing my codebase over to typegen yesterday and was also struggling with typing errors on my `ActorRefFrom`. I assumed it was me missing something.

**Comment by Andarist** [comment]
@christoph-fricke could you split this into 3 issues? being able to track those separately would make it easier to work with those.

For now, I've looked into the string literal case and I'm not yet sure what we can do about avoiding breaking changes. I already had a refactor plan for v5 that would just avoid this altogether but it's not an easy decision to use that strategy in v4. Potentially this could be fixed with overloads but overloads have their own set of problems that I'd like to avoid. We also could use `NoInfer` trick but that would break people relying on inference and using `config.context` to type this (instead of `config.schema.context`). 

I've put together a simplified repro case for this [here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwgFgSwDYBMYHsB2wIA9hQC8UA3gFBRRII4BOAhkgCoQDOwAXFAEQDu6tANYJMAc25QAPj0zpgAWn5CR4sgF8yZFBADGSerWh76rVlACy9HYkwQAPEwzY8wAHykKUAPpfHXR1g4+Oqa2saGUABmAK6YOsAIWFA6hvQ4ltYiEABMDk5BbgAUOliRCKJc5JQlzvgA-P75LgA0nqzWEAC29A0elNWBLr0BtcCeGmoAlFwZNvYjBa6aKRBpELNZ2YVVUO1wXfSVngOjlWpQJrCIqE34rZRq98mD+Ef9VDQQDMxsnFAA5PRMCBgDZRP9xupJstUukrHMtjs9gc3v0agUzhczPBkGgXsAno9POiXKjKNQ6IwWOwuIDgaCVP8sc9MOxIVNNAB6TlQUHQABGEDg9AAbolaBd+egRdAEGZWNFaGBaHKVFBBTp6NFWNAAJL-FBQPCQeJQGi89DqoWi6DUQTQCA0fYS6nAACMAGpXdkoAIoK6AMxe34AFjI3PV0QI5tYAgI6EiVuFMrMduggeD7DdmlAkCgABlPt8AKqYRKYIg8JTCMQSaTcWQKasqbhkXPp35uyuFylIUvlqAAMl2wBVYnDPKgAD06jnwB32D7iD2vox+0lh3SQWCIRHp7O2-P-b8A92i2uy0lpOwx6IJ5QZ3O866Q2fe+uK9ItwyxLvJ4-DzzAA5dBdUwSIvgcdxiAAbSYABdOCjXwCBMBQMwgRAKA6igAAGKAuFsGVaHg0JdH0CIYjiBIkhWNYNlsAM8nxVxilKcpURJeouBAsCINoZjRlcJ5kW6XodhOAphluMYHihGZ4SyQTFi5HlLl4IwgV2CBoGdaBtTVAADXjwK+QznmiVAoH2JAwCgbUyDouFMkY7Y2g6boyRZDFSHOS4cRufFCSeLi-gkj5e1dWlMJ-cF2WhRzYXWRTXKRDzDj6NF8UxfzrjxUZguJbLMvJc8fhpAEYp3ZkajZOSOXvfkozNAh+Esw1+VSQRdnS+QkDYMxuhcthHKwdgoE6SsnOS4aAzcyhRIy8KI1CnLsTymTCsk0kSoi1dyr+b9qsuWrZKgCZoU6e8ZyAA)

**Comment by jonnyirwin** [comment]
I know this is going to be split into 3 separate issues, but looking at the issue with`ActorRefFrom`, previous to 4.29.0, using `type ChildActor = ActorRefFrom<typeof createChild>;` i.e. typing on the factory function (from @christoph-fricke codesandbox [https://codesandbox.io/s/floral-bush-yxn10?file=/src/index.ts](https://codesandbox.io/s/floral-bush-yxn10?file=/src/index.ts) ), would have worked. I think it now works changing to be typed like this: `type ChildActor = ActorRefFrom<ReturnType<typeof createChild>>;` i.e. on the machine, rather than the factory function.

**Comment by Andarist** [comment]
Issues 1 and 3 are both being fixed by https://github.com/statelyai/xstate/pull/3084

For the second issue, I've created a minimal repro case [here](https://www.typescriptlang.org/play?noErrorTruncation=true#code/JYWwDg9gTgLgBAbzgYygUwIYzQWQ8gC2ADs0AaOAQWRmgCU0AzAMSghAowGcvgBzYhS5gMAd2JwAvnEZsQcAOQAPLjCxoFcAPRa4MAJ5g0XAFxwALADoAzAAZLAJgBQThE7goIxVSnTqAwkQANgAmcAC8cAAUAJQRAHy+mNh4hCRoUQiSMQDcLh4GRnCBwKHUtFARVDT0TKzsADyFaBCMSQHBIfF5HjoeAHoA-PkyAK7ENMBe7dgAChjoxDBRAPohaGCmiHDCYsQloWaxCcWd5dBScVkjqMlo84vLSLviByFHceGJL8RRtx2lEKxOLZPKSFxuDzILw+NKhKr-FL4IikTKgkbNU6A86VSI4hgsORNQwtNpwro9bS6OBDEaMcaTaaI+4LNBLVbrTZmZ4iV6dD4nN44y6IcHuGYsx6ZHa8-b86Kfb6yv6dEG5JzgoA) and I have a fix locally but I need to think about it more cause I don't fully understand the relationship between those types

**Comment by Andarist** [comment]
Fix for the second issue is up here: https://github.com/statelyai/xstate/pull/3087
