### ISSUE TITLE
Bug: Sending events to an invoked child machine on `exit` throws when stopping machines

### ISSUE THREAD

**Issue by ptaranto** [statelyai/xstate#3053]
### Description

when a machine stops and has `send` action in its `exit` actions, the send action throws as there's no event to be sent

relates to: #2450 #2057 #2880

### Expected result

`exit` actions to be executed before machines are stopped

### Actual result

all ancestor machines are stopped except for the children of the state with `send` in the `exit` action list

when a machine sends an event to its invoked child on `exit` action, an error is thrown:
`TypeError Uncaught TypeError: Cannot read properties of undefined (reading 'name')` at `Interpreter.sendTo` on interpreter.js:134 

line 758 on `interpreter.ts` file where `event` is `undefined`

this happens on hot reload or when unmounting the context/component that created the machine 

when calling `machine.stop()` the thrown error is `TypeError
Cannot read properties of undefined (reading 'listeners')` at `Interpreter.stop`

### Reproduction

https://codesandbox.io/s/xstate-stop-parent-child-grandchild-tuv3nk?file=/src/App.tsx

### Additional context

xstate v4.30.0

**Comment by Andarist** [comment]
I'm just opening a PR that should resolve a couple of issues around exit handlers. I'm not 100% sure if it will actually resolve this one though.

The provided repro is not perfect because it's using `service.stop` like this:
```js
onClick={service.stop}
```
However, this method is not automatically bound to the interpreter's instance and thus it really should be used like this:
```js
onClick={() => service.stop()}
```

When I introduce this change to your repro then I don't see any errors there. Could you tweak this repro case to showcase your problem in a better way? Initially, you have mentioned a completely different error:
> TypeError Uncaught TypeError: Cannot read properties of undefined (reading 'name')

And this is probably what we should focus on here.

**Comment by ptaranto** [comment]
@Andarist Thanks for spotting the error on passing the onClick callback, I've adjusted it and uncommented the exit field that will cause the exception

**Comment by Andarist** [comment]
I think that you might have forgotten to save this sandbox. However, I've followed the steps that you have mentioned and I see the issue now. This one (the crash) will get fixed with: https://github.com/statelyai/xstate/pull/3126 

I wonder though... do you expect that even from the exit action to be received by this grandchild when the child gets stopped? This won't work like that when this PR lands, see the comment I've left here: https://github.com/statelyai/xstate/pull/3126/files#diff-fc91146eff717b2bcd6adbc0955ca0549346ad7bef9aa2278e0a75a9793a66b9R625-R628

**Comment by ptaranto** [comment]
in my usecase, the grand-child machine works as a logger, so when the child machine leaves its state or is stopped by an external event, the grand-child machine would go to its final state in order to execute its own logic

I'm open to suggestions on how to handle this in a better way

**Comment by Andarist** [comment]
This doesn't tell me all that much about what kind of logging this grandchild wants to perform, why does it try to perform it, and why this logging is bound to some state of the parent machine. It's hard to advise other solutions based on such partial information.
