### ISSUE TITLE
Context unknown following typegen file generation

### ISSUE THREAD

**Issue by harrisonstern** [statelyai/xstate#3079]
Just migrated to using typegen in my project and for some reason following the generation of the typegen file, the type of my context throughout my machine isn't recognized. 

```
interface StateContext {
   data: Item[];
   total: number;
   query: Query;
   selectedSubItems: SubItem[];
   expandedRowIndexes: number[];
   hoveredRowIndex: number;
   modifiedSubItem?: SubItem;
   addToParentItem?: Item;
   error?: any;
}


export const stateMachine = createMachine(
   {
      tsTypes: {} as import("./StateMachine.typegen").Typegen0,
      schema: {
         context: {} as StateContext,

         events: {} as
            | { type: 'DATA_UPDATE'; data: Item[]; total: number }
           ....more events
      },

      context: {
         data: [],
         total: 0,
         query: defaultQuery,
         selectedSubItems: [],
         expandedRowIndexes: [],
         hoveredRowIndex: -1,
      } as StateContext,

...states and actions
```
![screenshot](https://user-images.githubusercontent.com/5498790/155171187-493a8aba-a6b3-446e-9cc8-f1ad7f078b9b.jpg)

"xstate": "^4.29.0"
"@xstate/inspect": "^0.6.2",
"@xstate/react": "^2.0.0",
"typescript": "^4.5.5",

XState VS Code Extension Version: v1.6.0

**Comment by Andarist** [comment]
Could you prepare a minimal repro case? Copying your machine and the generated type into codesandbox or TS playground would suffice

**Comment by harrisonstern** [comment]
@Andarist 

https://codesandbox.io/s/gallant-babbage-to4iw0?file=/src/TestMachine.ts

Not sure how to get the sandbox to work as it should with tsTypes, but this is what seems to cause the problem I see in vs code. For some reason the inline assign that occurs in the invoke onError causes all references to context in the actions section to lose their type. If you move the assign to a defined action the problem goes away. Maybe that is as it is intended...idk

**Comment by harrisonstern** [comment]
Just removing the onerror section will restore the correct type to context in the actions section

**Comment by Andarist** [comment]
@harrisonstern I think that you forgot to save that `TestMachine.ts` file because it's empty for me ;p

**Comment by harrisonstern** [comment]
@Andarist  Sorry for the inconvenience. It should be there now.

**Comment by Andarist** [comment]
This particular problem is going to be fixed with https://github.com/statelyai/xstate/pull/3082 . **However**, this demo is not using `strict: true` in `tsconfig.json` and that's the only TS setting that we are aiming to support explicitly because it's nearly impossible to support the full matrix of possible TS settings. That being said, for the most part, if we make it work with `strict: true` then it should work with other settings - the experience just might be slightly less safe at times. Don't quote me on that though 😉 

So while this PR is going to fix this issue... we still have work to do to fix the overall issue with the strict mode. We already have some ideas about how this can be done but we still need to experiment with them more.

**Comment by harrisonstern** [comment]
Thank you for taking the time to look into this. :)
