### ISSUE TITLE
Bug: typegen types resolving events to never in guards/actions

### ISSUE THREAD

**Issue by SimeonC** [statelyai/xstate#3102]
### Description

I only have this occurring in my one machine and it's fairly difficult to reduce down to a easy reproduction as I couldn't figure out what was the same between the errors. I attached a Typescript playground illustrating the issue with the working actions/implementations commented out. (The typegen is amazing BTW, so much easier and I can remove a lot of checks, looking forward to a CLI tool ✨ )

### Expected result

Event type should be correctly inferred for all actions/guards

### Actual result

`event` is resolved to `never` in certain guards and actions.

### Reproduction

[Typescript Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQWQ8gC2ADs04BfOAMyghDgHIAPAZxizQYG4AoUSWIjgYWLYAHNiFarXoMAAq3bYA9KBBoo3HjxUq4AFSItqwADZkA7iOEBXGHSzBkGM2YCeccWlJQOAEwA6OABRf2AYE0tzMzgAIzIIADdNSygI7GIdNCYBeBJsKCp8MgN3MDRvYgAGRB44RnlFNg4VGHLKnwYALjgYKFs0Xga0FOJIgGEMWzFicQBBZBhgCGIWXoR6hrh0EGS0AHkwZdXehgAlEJwDgDUQhjgAH0YAaRCATQB9S+u77W24CwfP4JgQMHM0Gcfrd7k9Xh9vlcYQ9ngx-tt0FQIMgZmc3l9oX9htsSBEcKSQLYQEcTmszuiRmtbOgbsBYLZXABJYhgez0uEMABCABkAKrnFGMCYACXmADkAOL3YmMljMtAAMWxMzQ-k5-jOGoOE1FAGUGdRtSxRWA8QjRQAFC1YnEsAAiEEsxDtXzdBwA6nKLTkIqz2VyeXzGCLxRbbGB-BwaStvVLZYrlVsGrt9mGYByzNzeTAzjL5UqLUCYHmC0WowwyxmLcgLBgoDWI8XS+mKyqUK2oFrXbr9fzUTGJcTyMSCppiK4QmNIhss4wekJ2hV+dPV8wWthAqSYOukJvIYwlBxD8QIg8dw173ASEkIABrNCmqDIOUYDR4W2II+IDAKIJDiJy4AWBo4xOKs6x1AC+C0vBDBAsQIJghClaaEkzhoPBpApFAfbiByUD+ARoyaH2-hoGYGDuJRRFTsSVHjCwUwzGBpo4Xh8EII+bGTNMsziAqZEUSuALiOgHBQEY4LkjelIgFCSJ-AK+KIr8mbSbJhQKcQIQAI4FngTCgFS9J9hYoiGUplmqWufYgcKIgwMmpyMEaJrmi5LAdmYnmpgwPlmhaIEhOA7TduWukUKxS4cSJYFunRDH8UBWCEPhprKPh3SrqiR4MEVjDoGwpUAqimJWlV2yoi6Or+PVDSNVauqBLh4ZmK1ApNUCQTENAICuH17XDv4bmVWVSADbqAD8ZzdfmY0CsNUCjb1CVbOw4hMdRPDkDoehwHlbbwLJsRUOYaA6Lo+iWGQo3vsIbhwEJJg5JkFF9MYgIQH9WBwE9KDgjsdGeKsf1kEJcBJK4gxPlIMAEGQSEpiwD3COhXgSSY4L+HA-irAw8CkLqfSA5Y0BQJ4GBxBA9iAu4xDIGBgL5fEaAwE9PjE8AVBUJoPjwGA9HIPhfDjJoxSS3AgoiGgi6iwhT4Gpz6RzMSZjYq455sFr4i8Md0uFHLZCguC3gq+MH1MD9JiK0CtvwJsDRnrFTbEgjZiDL0htgSbOizkUJRwNyhQY6srv247CtK7H7t9B0ZwTpKoXGuFAqErCzwAAZaQAJAgFzqXnjCOhnfqBgw5D58HPA5HkKBwfAEDHCmGrAHRFF4IQJBkAAvFsKgAFRj3AzT5QAtPR7hM-AcoACycuIYDiAAUuIACsIB+pyEw7wAitKr7zAc8wABrzGY3iWNK7zzJy8xMAYODzAqlh326YByv4cpqiCmAOcUUNw4j+gOMQK+m9z5umqMfEIy95hQHmCEAAWi8eYSQxJPwAOwak5IKFgVB5iCgAF7AHmMKeY8x3joM-gQMhDobqbyvgANhuMfdwpokjSmAAARhwAAamPhqAAnMKEAMANQACsmAhFNDvF44gJjIGXm6Y+LBxBugmPMLhboXhXwmKwcRYAmCcgdA6chEwIAEGFKaV8xAXgvGMgQPwwBBRxHcIWYyIBj6yM3iAFRgocA4FkZyHeAioDvHeNKSJr4NSb3OLYT+cQn44CflAKA8DiBQGXoKd4oppRAg1O4AAHBMEyppOQQGFMAAJZhgCmnEFfdwx9xAvAwAccQsj3AHEwaKQUEB3juBeEkTk7hXwTNBAYd44h-DGSviEHeXCBFujiBMY+ZgyFUgmHgiA4jj4TAVGAB0x95gdPmO4B04hBQqIYiTDA8wjnGRgC8OUm9nDnHcMgY+O9pSbzdJyAwBhziCgVC8U0NDLA73OGUNA5wXg3AVDU4yeCQgQEvngg4ppZHSnOGAYgpo8FXwOMvB0wpLDzC2fMcQCwd7zDdFQjUGoHQsBCAcOUAiQjEOEckwJExN4HGBTcCYr56UEBeIc+Y6CcBvIEccJgwDxHLGIIKG45T8CcmSd+VpZCEg7wdDcZeVB-BgCoCETk2jRTGVNKaeY5D3imlFCEcpEBzjlJAOgrZBgWBJAIAAJgIP8h0sid4THOOIYyNx5niGXrYG4Aj5jBNWcZWRV9XzsJqEwYgQsbjkI1C65ABg9HHOFJvF4DoCBKnIR00Udj0HCk5Ewcpppj6mk3qaD51QCDyuXsI-0x9KjzAwAYMAaDqjzAdBAYRtCXicjiAI945x2EYAAMzoPYe4EIGBqiigCu4AwtgDAajAK+SwSRqiyJgDgKgZRA2BpeMI5A4jziBvERMGAwoNSoDIRqc+goBEvGIAIvecplVQEUQcYAPCXhxHKTPdh5xN6YIweQqgwpVhxDxYG9wvziVugdP6dhlhBQEDMKZARAj-C0bQOQ84poe5ynESEORBwDBuhwCAEIlgbkTGEeIJgEAIAYGAAqMw7wNR4NsOIf0V9jLrqYeI9hYbbjvGFGqOIy8Z4HBCCwdweCwDH3OCsCZJ6FQOlfOcQJ1mIAamMtKSwrqJhuhANUORSQWBgeXkFfwFLxCWHEHu8Q-SwA4FsMIpIlg4ivggGgAgBwzAKgOEiq4IQeFulfO4dBbpbDnE5C8UUVAFQKiYI5kA4iFTxKYBMQhx9LDCnIUkcjwjjITAmJySwLbpQZYIMZbjIB3g7wVK+MAsjTTvHYal-wUBzggGFDetA4jBR8IdRMfDtCFTYmQJYeMUB5F6PcM-YyBgmAI3mDWqAExxubzAOg5A7hHS-gwBAcCm8g1gBeDgBUgb3jIBeAqG4u9yF+3QWAaUO9BRDPTa+RM5TZHiJTRqKA-o3QGYgKfa+Ewr7qpuPMao0pj4gCvrqMwM9N6MsiQqZYGBN4QBeAYKFftOTCPEbG5AOBkuigVDgDV5SDAgHcOGzkr4cB7eMuDmtWbvUwGIF6G4V8YDLrdKzAR5ym0hrMIGq9xROMKmXjWtAnI8Gb2FGx94ZguPvAEWYG45wDhTOEQQZANxLDrodMgBU1Q4i2E5MZY+33N4z3+YVzk1QzGcgVOQ18gu0DE+FAqdw67Fcgi+8AYy7DjKvgmOIgzIBN7HySIkhU4jyRvdFOuiPWbN5mGFLYpI7DbEYFNAQcQeD-DnHeKfdHx8YDoPcCjwgdXjL+lkRMcpuRgAuKYFAYhdK2HnCvv6ADFl9P+gMJvao7N3g3DlL009UBpRUEDbYHAxBiBZoUeItAyADgECoO4TkGphSCgmEkEAyAC-vEsB1m4ZgmF5g4Ax4VAthUBMBsB+4iBSAAAKVcZOAESIMoCoTKYQEwZAzoGoAAGlXAaBYBylGikgBG2GQFWGwAdg2EoBsAQOIIaCPGAFcCwxcAsADn6CDlwOIPmj1H8CWk1nYNoIBBWgLGCn1F4MDm1g4IBA7mQl6HOFv2gH8AAB5xDxAsCcZ3AAA+AAbQAF0+wARyAcCBCPokpKC0C4ArYIRY5nhI5NBo4jIlwODDCODgANYGBgo4Bu5e4WAGAjDiD6DXAzgSo-CAR9wCo1ZaCjwiDjDXBrBGJegtDJDiCaDjCGhSD0IzgZIIDNBDITIzIMALIVJfCkjaD2AoBvASxGAABiDwrwswCiQICqY8Eo7YZw1I7YFI1I+w+CLQhgI8ByFSYKHwtQ1CYESw7wBgHQkI9o1uDIxgWyFgeyCkKkYomY7YMoios4GozuaGOohopovqYwtomYzomIpYTGM4HwNUFkNkVaQsSMY8aY9ojYnmLY2onueolgRo-CZotY46donQpI442gpo6IgQ0WOmM4FsTAQcDqbg1Y1IryU44gsKU0BIlogEZE4w9Itw1ydyYKBEtYj2NsTY6o947wwILg6aR4jE4g7ohIhgK49UIcZqfUSY2kh8J41IrEgQnEoIgKW44QnY4gQkokl4yohgbY2kTwj4horgrqQUsaLk9o+kuAXopk9AFkwaNkwEokigZUgQnk0okk14sk4UmUik+UjaLaUUtY1U9UpkTUuEnUjkigWk3U1I-4gQ4E4g2qV0ME2gpE2k1E9EvUo04gvkxgPEtgAkg04w8Ut480vYr4qk9yQ4z0uM5I10tI1YXEgUnqWM7MvoE0iUqUlMC0z4ykuEhUnqdMo4zMzEoshMs06U5MqsyaQIa0saV0r0gElo3s4gn0gELggM4gkMCUtCDCa2TgTMsI-iWkoQwIiImYoMvUhoCcUcu084uCBk8cwKOsR4xgDUtAfch4yYhsgQ5syU8kysg4osocmYxsJUUMtchocMs4mQtUhgeMRMbAWM8qNAPYFIU84sc8osgESMvojlaKdwW0tcq8ss3Y2UlM6sxc3qcC-UjC98gQ+078hMJMYU3wo8x0k8xU+40CqYjC4k8o0068pM5C9s5qGsu4usmYgctYj0v42kh82grsswTcgQ1ctcjc5cvUhCm8-Yn41i+sosp8kIASlU7cukRgH8gi2kOCtY8S+iy06svi6S70ns7i-szMoS9orSR0BSukpSlCAaG0DSy8ksxM1shirg-Szk2krSGuOUSyxCays4AaD0L0ey40mi0siSlCyaNyt09o9i1og01MtgSy8cs4Sc8Ymclo0y1I8yh0Hy7YVUhgWysAYK4grS5ynSyaakqKni4gzygMby0SrovyxgAKz0EUi86i0kuisqyshK34tii8uSl8tY7ChoXC1Sv8wikYqsEC+wMC18yCyKGC4qkKzqxCqQNs3qqK9ysMossa-Cia9SkY6EtsGa48Si180q8sjauEyqwyjii8kS7Cy6pCiku8rimKoEpwrkzKgEXOSy3CnMFIf80Y9CNKua1IyCrIuSJY5SFYzM569a5C1i6qrSP6hq3yz83ov0mYIihgQGw4SaxgVKzCCY86iG3MzI-SHIzCAYuGlohGisySgaZGpw1cH0zo0iNsSSdGp8fMu44KXoGA9I8gmANQoSAASjgCHg0J5pGCXC4DgFOhYAICZnqO5gjhlj8CUtjmgAThdkcPaNOjgAAD0FoWj0B8woApAhJDwiYh57bZiRbmKhTaR9R9C4qkjFrjh3BBbhbvoxalxJbpbZaTDRZ3aAQjbTbzaeZmQpBigzAgRw7orByuTVTkT+jljqRhT4IRAxBJAYChayDvo3Q-AqBRbQ7xgg6ZaeShIk6GhI6zajjxaDTsb4JC6ZYHYA7RYq6Q7a6WiG6gT4qrQbRfai7O6K6YAe6a75b+79ATbG7vSh7XRArUx26Rau7K6pbq6Wi+7Da56o6ZLsSBwtSRwNZc6JBiAC6-aHYS6MAy6p6d6Z696GgD7vTm6kjjyT7uDehz78617i7S7y6Jat7e6n7UiB72jr6YBb6y7GLtS7aJ7bak7yB37jDxqCbaQf7QI-6oGYGgHA6QHp6w7Z6X6F7aCUGW7AL9gBa0C87L7-6b7AGN7J7CHH7iHn756gTUHwSLJqwyKDysG6Gr6x7oGmGJ6H72jd7wH96yHBzuHaDjzTrBGL7hGO7RG778Hu7WHJGwHjCIG37KGgLSKeoBHaGVGGH1Gy7mGJHUipG9GZGuGDTjr2x+GHjlGcGRG8HrHtHbHdGBD9HyH5HiDprXGuwzGPG1GvHxGfHjC7H-GHGm7WaDCthxbeAgA)

### Additional context

xstate 4.30.3

**Comment by Andarist** [comment]
Huh, this is quite interesting! So it seems that the issue is within our `IndexByType` helper that is used behind the scenes, see [this TS playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4QKIDcLjIDeAUMssACYBcyGYUoA5gNxnIA2A9gnBxLXqMQrEgF8SJUJFiIUAYQAWcETnyEIAD0ghKGNJjUEwxdmACeABwHIA5PIASAQQByAcWy225XHwCuNkLMbBJS4NDwSMgAkuFQiGDAXCB4xshaOnoGWKmEpOQW1rS2qAAyAKoASrbIAD52AGIA8vLlAMq24pKFKLGUWqjmACpWEAA8Q+naBFlEyD2CDMzIYgB8yAC8puQA2gDSFCDIQzu2PbYAuhe02NrxCGATADTE86O0B2shklqWXFAmHrIACy5lyYH0Wz6A2GozGShUTCMhHqsRkCSSKXUYFWJAA9HjyETicgAHoAfkkQA). The issue here is that it doesn't process event types that are unions correctly.

A different version of this type works OK, see [here](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4QKIDcLjIDeAUMssACYBcyGYUoA5gNxnIA2A9gnBxLXqMQrEgF8SJUJFiIUAYQAWcETnyEIAD0ghKGNJjUEwxdmACeABwHIA5PIASAQQByAcWy225XHwCuNkLMbBJS4NDwSMgAkuFQiGDAXCB4xshaOnoGWKmEpOQW1rS2qAAyAKoASrbIAD52AGIA8vLlAMo19QAGANLYAJoA+gAkRLblAAqddgAiTQDqLrZiXSGShSixlFqo5gAqVhAAPHvp2gRZRMgbggzMyGIAfMgAvKbkANrYFCDIp5jIbAfABEG2BAF1wbRsOJJFpLFwoCYNsgALLmXJgfRvLY7faHI5KFRMIyEeqxGQJJIpdRgR4kAD0DPILNZyAAegB+SQkIA). Key remapping for mapped types was introduced in TS 4.1 though so I need to rethink compatibility implications here or figure out a different filtering strategy than using `Extract`. For instance, an intersection works quite OK, see [here](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4QKIDcLjIDeAUMssACYBcyGYUoA5gNxnIA2A9gnBxLXqMQrEgF8SJUJFiIUAYQAWcETnyEIAD0ghKGNJjUEwxdmACeABwHIA5PIASAQQByAcWy225XHwCuNkLMbBJS4NDwSMgAkuFQiGDAXCB4xshaOnoGWKmEpOQW1rS2qAAyAKoASrbIAD52AGIA8vLlAMo19QAGANLYAJoA+gAkRLblAAqddgAiTQDqLrZiXSGShSixlFqo5gAqVhAAPHvp2gRZRMgbggzMyGIAfMgAvKbkANo9FCDIex8AIg2AIAuiDaKcAGTEa6HWjfCShLSWLhQEwbZAAWXMuTA+jeWx2+0ORyUKiYRkI9ViMgSSRS6jAjxIAHoWeQOZzkAA9AD8khIQA).
