### ISSUE TITLE
Bug: useMachine actor and InterpreterFrom don't match with typegen

### ISSUE THREAD

**Issue by SimeonC** [statelyai/xstate#3138]
### Description

The following code generates a typescript error when it shouldn't. (Typescript playground link has full TS example).

```tsx
  const Component = ({ actor }: { actor: InterpreterFrom<typeof machine>}) => null;

  const App = () => {
    const [state, send, service] = useMachine(() => machine.withConfig({ actions: {
      update: () => {}
    } }))
    return <Component actor={service} />
  }
```

### Expected result

No errors shown

### Actual result

Following typescript error was given;
```
Type 'Interpreter<{ expiry?: number | undefined; }, any, { type: "UPDATE"; }, { value: any; context: { expiry?: number | undefined; }; }, MarkAllImplementationsAsProvided<Typegen0 & { indexedActions: IndexByType<BaseActionObject>; indexedEvents: MergeWithInternalEvents<...>; }>>' is not assignable to type 'Interpreter<{ expiry?: number | undefined; }, any, { type: "UPDATE"; }, { value: any; context: { expiry?: number | undefined; }; }, Typegen0 & { indexedActions: IndexByType<BaseActionObject>; indexedEvents: MergeWithInternalEvents<...>; }>'.
  The types of 'machine.getStateNodes' are incompatible between these types.
    Type '(state: StateValue | State<{ expiry?: number | undefined; }, { type: "UPDATE"; }, any, { value: any; context: { expiry?: number | undefined; }; }, MarkAllImplementationsAsProvided<Typegen0 & { indexedActions: IndexByType<...>; indexedEvents: MergeWithInternalEvents<...>; }>>) => StateNode<...>[]' is not assignable to type '(state: StateValue | State<{ expiry?: number | undefined; }, { type: "UPDATE"; }, any, { value: any; context: { expiry?: number | undefined; }; }, Typegen0 & { indexedActions: IndexByType<...>; indexedEvents: MergeWithInternalEvents<...>; }>) => StateNode<...>[]'.
      Types of parameters 'state' and 'state' are incompatible.
        Type 'StateValue | State<{ expiry?: number | undefined; }, { type: "UPDATE"; }, any, { value: any; context: { expiry?: number | undefined; }; }, Typegen0 & { indexedActions: IndexByType<...>; indexedEvents: MergeWithInternalEvents<...>; }>' is not assignable to type 'StateValue | State<{ expiry?: number | undefined; }, { type: "UPDATE"; }, any, { value: any; context: { expiry?: number | undefined; }; }, MarkAllImplementationsAsProvided<Typegen0 & { indexedActions: IndexByType<...>; indexedEvents: MergeWithInternalEvents<...>; }>>'.
          Type 'State<{ expiry?: number | undefined; }, { type: "UPDATE"; }, any, { value: any; context: { expiry?: number | undefined; }; }, Typegen0 & { indexedActions: IndexByType<BaseActionObject>; indexedEvents: MergeWithInternalEvents<...>; }>' is not assignable to type 'StateValue | State<{ expiry?: number | undefined; }, { type: "UPDATE"; }, any, { value: any; context: { expiry?: number | undefined; }; }, MarkAllImplementationsAsProvided<Typegen0 & { indexedActions: IndexByType<...>; indexedEvents: MergeWithInternalEvents<...>; }>>'.
            Type 'State<{ expiry?: number | undefined; }, { type: "UPDATE"; }, any, { value: any; context: { expiry?: number | undefined; }; }, Typegen0 & { indexedActions: IndexByType<BaseActionObject>; indexedEvents: MergeWithInternalEvents<...>; }>' is not assignable to type 'State<{ expiry?: number | undefined; }, { type: "UPDATE"; }, any, { value: any; context: { expiry?: number | undefined; }; }, MarkAllImplementationsAsProvided<Typegen0 & { indexedActions: IndexByType<BaseActionObject>; indexedEvents: MergeWithInternalEvents<...>; }>>'.
              Types of property 'machine' are incompatible.
                Type 'StateMachine<{ expiry?: number | undefined; }, any, { type: "UPDATE"; }, { value: any; context: { expiry?: number | undefined; }; }, BaseActionObject, any, Typegen0 & { ...; }> | undefined' is not assignable to type 'StateMachine<{ expiry?: number | undefined; }, any, { type: "UPDATE"; }, { value: any; context: { expiry?: number | undefined; }; }, BaseActionObject, any, MarkAllImplementationsAsProvided<Typegen0 & { ...; }>> | undefined'.
                  Type 'StateMachine<{ expiry?: number | undefined; }, any, { type: "UPDATE"; }, { value: any; context: { expiry?: number | undefined; }; }, BaseActionObject, any, Typegen0 & { ...; }>' is not assignable to type 'StateMachine<{ expiry?: number | undefined; }, any, { type: "UPDATE"; }, { value: any; context: { expiry?: number | undefined; }; }, BaseActionObject, any, MarkAllImplementationsAsProvided<Typegen0 & { ...; }>>'.
                    Types of property '__TResolvedTypesMeta' are incompatible.
                      Type 'Typegen0 & { indexedActions: IndexByType<BaseActionObject>; indexedEvents: MergeWithInternalEvents<IndexByType<{ type: "UPDATE"; }>, { 'xstate.init': { ...; }; }>; }' is not assignable to type 'MarkAllImplementationsAsProvided<Typegen0 & { indexedActions: IndexByType<BaseActionObject>; indexedEvents: MergeWithInternalEvents<IndexByType<{ type: "UPDATE"; }>, { 'xstate.init': { ...; }; }>; }>'.
```

### Reproduction

[TypescriptPlayground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoUSWOAbzSJRiQFl0ALYAOyQBo4Akl2ZQwREQDEceAL5xsuAgA8AzjCZIylcNHi04AVxWsO3JHDkK8+AAKr1zAPSMS5SsKRRM6cwBUAnmBIAOZIXAAMdORwBDZ2ahqOMIEhYfgAXHAwUAZIFDFIAG5hMCoAwihG3MEAghjAEFwqmbTRMYZgACYamfgAqgAKACI1vgCiWjEy+XDcIlwoADZjxcLNUe3KCcwAdNzAMBl0WSm99hp7XAf4FjPTbdyFEADWSADKUGgAciggJmAte4xEDAFQqaoCcCLJB-YRMBpNFptGLoGAI9b4AxdDSTdrGKCFYBoJDrHjFKAzGLBAwoKCdUlFTyUuCdJCLFD+Bnku4zRlrCpVLjBN6eQnE9a0IFwPmlAXgoUAcRpdIlUpl5Uq8uCQzZHNVMxATDQ7BJbwcJN6+0OM3UwS5TPIMjcaEaajghuNZjgAF4YgxUMw2J6eAAKZEbTZZFQBIKquAoFRwGOpCK8cMxFTGmEoJGR9oujxKGCA+OJ-RIJRgYBQfwAfkyXAMIAARkyLGm8wVVqUSwmI52TkFeoMRuNcXmnROO5GrcAlparodp5tgJ1eiGPZweABKfDLvHmiXp9pW3MDuCNM-nuAj0ZjK-X+P1V29LHdZj4Y8Tr-tSedv+bABFhtNuFBtAWbplLgkA8MIPpwCG+iotAFgtE+MDQJkQgiGISCSNIAA8yRBBAmDuqYPAAHwyNuPqUXAjaLIsYF+q68A1GAYDwSGtHevRrSbBB8AANrbHwcDGFwnT8PiYpIAAuvBRgmMGSAhjxdHkapOwAO4HOwUFcJgwDBIh6Hog+MRvj0CG8fxQFyDR27huIBhQFwcAEVBOiwfAyFQN6tCyUSSByI4lFtDIQA)

**Comment by Andarist** [comment]
Instead of using `withConfig` together with `useMachine` you can utilize the second argument of the `useMachine` hook, like here:
[TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoUSWOAbzSJRiQFl0ALYAOyQBo4Akl2ZQwREQDEceAL5xsuAgA8AzjCZIylcNHi04AVxWsO3JHDkK8+AAKr1zAPSMS5SsKRRM6cwBUAnmBIAOZIXAAMdORwBDZ2ahqOMIEhYfgAXHAwUAZIFDFIAG5hMCoAwihG3MEAghjAEFwqmbTRMYZgACYamfgAqgAKACI1vgCiWjEy+XDcIlwoADZjxcLNUe3KCcwAdNzAMBl0WSm99hp7XAf4FjPTbdyFEADWSADKUGgAciggJmAte4xEDAFQqaoCcCLJB-YRMBpNFptGLoGAI9b4AxdDSTdrGKCFYBoJDrHjFKAzGLBAwoKCdUlFTyUuCdJCLFD+Bnku4zRlrCpVLjBN6eQnE9a0IFwPmlAXgoUAcRpdIlUpl5Uq8uCQzZHNVMxATDQ7BJbwcJN6+0OM3UwS5TPIMjcaEaajghuNZjgAF4YgxUMw2J6eAAKZEbTZZFQBIKquAoFRwGOpCK8cMxFTGmEoJGR9oujxKGCA+OJ-RIJRgYBQfwAfkyXAMIAARkyLGm8wVVqUSwmI52TkFeoMRuNcXmnROO5GrcAlparodp5tgJ1eiGPZweABKfDLvHmiXp9pW3MDuCNM-nuAj0ZjK-X+P1V29LHdZj4Y8Tr-tSedv+bABFhtNuFBtAWbplLgkA8MIPpwCG+iotAFgtE+MDQJkQgiGISCSNIAA8yRBBAmDuqYPAAHwyNuPqUXAjaLIsYF+q68A1GAYDwSGtHevRrSbBB8AANrbHwcDGFwnT8PiYpIAAuvBRgmMGSAbhR4kCZGqLog+mxvj0CG8fxQFTOGNHhuIBhQFwcAEVBOiwfAyFQN6tCyUSSByI4lFtDIQA)

However, this works somewhat accidentally - or because I didn't predict this combination of things.

It's because your machine initially is "incomple" as it doesn't yet have access to all the required implementations and you create `InterpreterFrom` based on such an incomplete machine, so the embedded typegen data in that type is the one that still expects some implementations to be provded.

When you are using `withConfig` you are actually returning the "complete" machine with everything provided and then when you try to assign a "complete" service to an "incomplete" one it isn't accepted as thos are incompatible.

The funny thing is that `useMachine` might return... "incomplete" service because it's creating its type based on the input `machine` using `InterpretFrom` and not based on the "complete" machine that is always implicitly~ created by `useMachine` (as `useMachine` makes sure that you provide all the implementations before you can use it).

I'll prepare a PR in a moment that should help with this a little bit and gonna ping you there.

**Comment by Andarist** [comment]
The PR is up: https://github.com/statelyai/xstate/pull/3139
