### ISSUE TITLE
Bug: Schema of context defined, yet not recognized in action

### ISSUE THREAD

**Issue by saikatdas0790** [statelyai/xstate#3287]
### Description

Trying to follow along from an example [here](https://graph-docs.vercel.app/actions/context#updating-context)

The schema is defined in the context but it's not detected in TypeScript and the context property is shown as undefined
![image](https://user-images.githubusercontent.com/7412443/168004109-059a3299-2d90-4903-9735-11e5d4f30616.png)

Here is a minimal reproduction:
https://codesandbox.io/s/currying-wind-4ohyf8?file=/src/index.ts

### Expected result

No type errors

### Actual result

Getting type errors

### Reproduction

https://codesandbox.io/s/currying-wind-4ohyf8?file=/src/index.ts

### Additional context

XState version: 4.32.0

**Comment by Andarist** [comment]
I think the problem here might be related to a certain circularity in the `assign`'s type definition that makes it hard for TS to infer this. 

As a workaround you can type `context` parameter explicitly, like [here](https://codesandbox.io/s/heuristic-kepler-ycgt3b?file=/src/index.ts). It's not ideal but fixing this in XState might take some time.

**Comment by saikatdas0790** [comment]
But wouldn't this also disable the typegen tooling completely? That's more harm done, no?

**Comment by davidkpiano** [comment]
Closing as the sandbox could not be found and may no longer be reproducible with the latest XState version.

If you can share a reproducible sandbox with the latest XState version, will reopen.
