### ISSUE TITLE
Bug: Unable to send event to child when using `respond` after invoking Promise in child machine

### ISSUE THREAD

**Issue by nik-lampe** [statelyai/xstate#3295]
### Description

I tried using the respond action from a spawned machine, that itself invokes a promise. This results in an error `Unable to send event to child 'invokedPromiseOfChildMachine' from service 'child-machine'.`

Thus using `sendParent` works.

### Expected result

Same as when using sendParent.

### Actual result

Unable to send event to child 'invokedPromiseOfChildMachine' from service 'child-machine'.

### Reproduction

https://codesandbox.io/s/xstate-child-machine-promise-respond-cijipq

**Comment by Andarist** [comment]
`respond` responds to the actor that has sent an event - it's not the same as `sendParent`. You are receiving a done event from that `invokedPromiseOfChildMachine` and you are trying to respond to it (and not to the parent of the `child-machine`. This doesn't make sense because that promise actor is already done itself and has been removed from the internal data structures of the `child-machine`. As a promise actor it also doesn't really accept any events to responding would be a noop anyway.

**Comment by nik-lampe** [comment]
Thanks for the clarification! 
Makes perfect sense now, once I managed to understand it.
