### ISSUE TITLE
Bug: Entry actions do not fire on external transitions from child state to parent state

### ISSUE THREAD

**Issue by Blacktiger** [statelyai/xstate#3409]
### Description

When marking a transition in a child state as "external", the entry actions on the parent state don't seem to be fired.

Given this example machine:
```
import {
  createMachine,
} from "xstate";

const machine = createMachine({
  initial: 'loaded',
  states: {
    loaded: {
      entry: ['logEntry'],
      initial: 'idle',
      states: {
        idle: {
          on: {
            UPDATE: {
              target: '../loaded',
              actions: ['logAction'],
              internal: false
            }
          }
        }
      }
    },
  }
}, {
  actions: {
    logEntry: () => console.log('entry'),
    logAction: () => console.log('action')
  }
});
```

### Expected result

I expected that after firing the `UPDATE` event, the `logEntry` and `logAction` actions would have both been fired.

```
entry # initial logEntry call when the machine starts
action # logAction called for the UPDATE event
entry # logEntry called when re-entering the loaded state
```

### Actual result

This is the actual sequence I get:

```
entry # initial logEntry call when the machine starts
action # logAction called for the UPDATE event
```

### Reproduction

https://codesandbox.io/s/mutable-microservice-m0ilfl?file=/src/index.js

**Comment by Andarist** [comment]
1. this is, currently, not a valid target: `'../loaded'`. We don't support reaching out to parent states with `../`. I'm actually surprised that there is no error/warning in the console about this.
2. as this transition tries to target something outside of its current state (even though it's its parent) it doesn't quite matter if you specify it as external or not - this is always going to be external. Because of the first-mentioned problem though I suspect that this is just treated as a targetless transition.

**Comment by Blacktiger** [comment]
The same thing happens if I add an id (id: `loaded`) and call it that by id (`#loaded`).

**Comment by Blacktiger** [comment]
It's good to hear it will be fixed in v5. I'm looking forward to it! We were able to work around the issue in this case by firing the action from the transition instead of relying on the entry action to fire so it's not a critical fix probably, but I suppose that means the action will fire twice when we eventually upgrade to v5.
