### ISSUE TITLE
Bug: sessionId changing when navigating away causing hard refresh of state machine

### ISSUE THREAD

**Issue by nlokare** [statelyai/xstate#3498]
### Description

I'm using `@xstate/react` and running into a pesky bug that I can't figure out. When the state machine starts and then proceeds to the next state, if I navigate away from the tab at any point and come back, the state machine resets itself. In the GIF I provided, you can see the `_sessionId` change after this reload. I thought this was related to scope so I moved the `useMachine` into a Context provider but that doesn't seem to resolve my issue. Any ideas for how to avoid this? I don't believe this is a React render issue because the only thing that would cause a re-render is the state machine change.

![xstate_bug](https://user-images.githubusercontent.com/5903288/182968317-453b4874-f129-4c85-9a3f-17b1ae4bcd58.gif)

### Expected result

I would expect the state machine to maintain it's current state and not restart when navigating back to the page.

### Actual result

The state machine resets

### Reproduction

N/A

**Comment by nlokare** [comment]
Update: I've tried to use `useInterpret` paired with `useSelector` with `shallowCompare` but that doesn't seem to have resolved my issue. Anytime I navigate from and back to the the page where this is running an entire re-render is triggered and the state machine resets.

**Comment by davidkpiano** [comment]
That's very strange. I'm sure @Andarist has some ideas as to why this is happening, or maybe there is another hook you're using in React that somehow rerenders components when the window loses/regains focus?

Either way, this is another good use-case for allowing "restart with different machine" behavior (even though it's technically the same machine) and improving Fast Refresh, since it's a similar issue (cc. @Andarist)

But yeah, can you check to see that another hook isn't causing rerendering of that component? That's my suspicion.

**Comment by nlokare** [comment]
Sure thing. I disabled most of the other hooks while trying to debug. I can come up with a more trivial implementation as well to see if that helps. I am using GraphQL mutations as service configurations that execute at various steps. I don't think those are the issue but I do make queries outside the scope of the state machine before navigating from IDLE to the first state.

**Comment by davidkpiano** [comment]
> Sure thing. I disabled most of the other hooks while trying to debug. I can come up with a more trivial implementation as well to see if that helps. I am using GraphQL mutations as service configurations that execute at various steps. I don't think those are the issue but I do make queries outside the scope of the state machine before navigating from IDLE to the first state.

Can you please share the trivial implementation/reproduction?

**Comment by Andarist** [comment]
@nlokare it would be best if you could share a runnable repro case or a https://www.replay.io/ recording with us. It's important to know the structure of your components and the relationship to machines here to investigate this further. 

My guess is that you have a machine in some inner component that gets unmounted when you transition away and that you expect the machine to rehydrate with its last known state when you get back on this page and when the component gets mounted again. However, you have mentioned that you already thought about it:
> I thought this was related to scope so I moved the useMachine into a Context provider but that doesn't seem to resolve my issue.

So the issue seems to be about something else.

**Comment by nlokare** [comment]
Hi, sorry I haven't shared a trivial implementation. Before making us jump down a major rabbit hole, I think the issue stems from our React app setup in general. I was able to repro the page refresh behavior on another page in production so I don't think this is an XState issue. A new Chrome update went out so it is possible that is the culprit as well.

I will keep this issue open just in case but I really appreciate how quickly you both replied to my inquiry. I'll post an update either way to keep you informed. Thank you.

**Comment by nlokare** [comment]
@davidkpiano @Andarist I have an update. It looks like our React app was reloading entire pages wherever `React.lazy` was invoked. I'm guessing there is an underlying issue with async lazy loading of pages/components that was causing the refresh. The page where this state machine was being used was a victim of this behavior. Thank you again and sorry for the false alarm!
