### ISSUE TITLE
Bug: Error loading external ".../xstate/es/interpreter.js" in Nuxt

### ISSUE THREAD

**Issue by Lexpeartha** [statelyai/xstate#3505]
### Description

XState/FSM implementation has trouble loading in (Nuxt/h3) server environment.
I'm suspecting this has something to do with `interpreter.js` ESM compatibility, although adding it ti vite's transpile depency, as well as creating alias that points to `es/` folder didn't change anything

When changing nuxt to fully static or SPA mode, for example with
```js
export default defineNuxtConfig({
  target: "static",
  ssr: false
});
```
Things work as they should

### Expected result

Expected server to run

### Actual result

Server crashes

### Reproduction

https://stackblitz.com/edit/github-yt6qk3

**Comment by Lexpeartha** [comment]
Tested with Webpack 5 as well, same error

**Comment by Andarist** [comment]
@Lexpeartha could you provide a webpack-based repro?

**Comment by Lexpeartha** [comment]
To use webpack just install `@nuxt/webpack-builder` as dependency, and add to `nuxt.config.ts`:
```ts
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  builder: 'webpack'
});
```
Not sure if it gives any more insights than Vite version

**Comment by Lexpeartha** [comment]
But if it does, I updated stackblitz

**Comment by Lexpeartha** [comment]
Actually StackBlitz had few error I didn't on my local machine. After fixing it, it actually seems to work?

**Comment by Andarist** [comment]
Yeah, it works now and I think that it's the problem of that Vite builder there. I've seen previously in the `.nuxt/dist/server/server.mjs` references to `node_modules/xstate/es/interpreter.js`. This was a problem because it seems that some module paths were "pre-resolved" by Vite. It chose to pick up files referenced from our `package.json#module` - but those are not compatible with node.js. So when the runtime used those references it failed. However, if this pre-resolving doesn't happen and the `server.mjs` only references `xstate` then node.js is able to correctly resolve things using its own algorithm (it chooses our `package.json#main`).

I don't think this is our problem to solve.

**Comment by Lexpeartha** [comment]
Thanks for pointer @Andarist - for anyone stumbling into this in the future, issue can be fixed by adding the following code to your nuxt configuration:
```js
build: {
    transpile: ['@xstate/fsm'],
  },
```
