### ISSUE TITLE
Bug: Error in Action not catchable (UnhandledPromiseRejectionWarning) causes nodejs to crash

### ISSUE THREAD

**Issue by gfauchart** [statelyai/xstate#3645]
### Description

Throwing errors in actions under services.onDone is not catchable, which causes the whole container to crash.

Throwing errors in actions under states are properly hanlded though, only services.onDone seems to be impacted!

Also, it seems that the browser version of xstate does not have this issue for the same machine config (according to codesandbox) the codesandbox below is for nodejs

### Expected result

xstate library should handle promise rejection on services.onDone like other actions

### Actual result

UnhandledPromiseRejectionWarning crashes the application on nodejs

### Reproduction

https://codesandbox.io/s/node-js-forked-pk9qvm

**Comment by davidkpiano** [comment]
Note to self (and @Andarist): this would probably rely on `state.onError`

**Comment by Andarist** [comment]
The crash itself when an unhandled error happens is the expected result. This is what node.js does by default and we don't intend to diverge from this common expectation.

That said - the error should be "catchable" somehow and with recent changes in v5 it actually is. You can use this to listen for errors:
```ts
actorRef.subscribe({
  error: err => {}
})
```

The `try`/`catch` that you were trying to use here just can't work. This error happens when the promise resolves and at that time the execution point is already **past** that `try`/`catch`. The error happens asynchronously so a synchronous `try`/`catch` just can't catch it.

I tweaked you codesandbox to demo how you can catch this (the `error` listener might be commented out there - feel free to play with this demo to see how it behaves with different types of error handlers):
https://codesandbox.io/p/devbox/node-js-forked-lwgqkt
