### ISSUE TITLE
[Typescript][@xstate/fsm] Config interface property 'initial' should be of type TState['value']

### ISSUE THREAD

**Issue by GTRanger** [statelyai/xstate#3648]
### Description

Under the current interface `initial` is defined as a string, but passing in a string that does not exist as a state in the state machine will result in the following TypeError due to [this line](https://github.com/statelyai/xstate/blob/main/packages/xstate-fsm/src/index.ts#L150):

`TypeError: Cannot read property 'entry' of undefined`

Since it is not possible to start in a state that is not defined within the machine, I believe that the [type of `initial`](https://github.com/statelyai/xstate/blob/main/packages/xstate-fsm/src/types.ts#L124) should changed to `TState['value']` to add type safety.

### Expected result

I expected `initial` to have type safety.

### Actual result

The `initial` state does not have type safety and results in an error if you pass a state that does not exist in the graph.

### Reproduction

Pass in a state that doesn't exist into `initial`

**Comment by davidkpiano** [comment]
I'm working on an update to `@xstate/fsm` that fixes this.

**Comment by Andarist** [comment]
Since on the `next` branch, we discontinued `@xstate/fsm` package (see [here](https://github.com/statelyai/xstate/pull/4265)) - I think that this issue can be closed now as it's no longer applicable. 

`@xstate/fsm` continues to work so you don't need to refactor your code if you care about its lightweight bundlesize.
