### ISSUE TITLE
Bug: @xstate/solid: Incorrect `after` event is firing

### ISSUE THREAD

**Issue by exclipy** [statelyai/xstate#3925]
### Description

I am observing that an "after" event being fired, for a state that is not the current state. The "after" event that *should* be fired for the current state is lost.

Go here: https://codesandbox.io/s/silly-margulis-fbmzd8?file=/src/index.js
Open the console, which displays the states and transitions as they occur.

### Expected result

The final state should be `NotHeld.Idle` because there is an transition to go from `NotHeld.TripleClicked` to `NotHeld.Idle` after 400ms.

### Actual result

It gets stuck in `NotHeld.TripleClicked` state.

Observe an event `xstate.after(100)#stepper.Held.HeldIncrement` but this is ignored because HeldIncrement is not the current state.

### Reproduction

https://codesandbox.io/s/silly-margulis-fbmzd8?file=/src/index.js

### Additional context

The bug does not appear if I use `interpret` from `xstate` instead of `useMachine` from `@xstate/solid`

**Comment by Andarist** [comment]
Unfortunately, `state` holds some data structures that are created internally by XState (such as `state.actions`) and when the Solid store is updated... it accidentally proxify/reconcile them and later on mutates them which has a very negative effect on our internals.

A dirty hack to work around this could look something like that:
```diff
diff --git a/packages/xstate-solid/src/useMachine.ts b/packages/xstate-solid/src/useMachine.ts
index 2afde4e9d..83cdbe485 100644
--- a/packages/xstate-solid/src/useMachine.ts
+++ b/packages/xstate-solid/src/useMachine.ts
@@ -40,7 +40,16 @@ export function useMachine<TMachine extends AnyStateMachine>(
   onMount(() => {
     const { unsubscribe } = service.subscribe((nextState) => {
       setState(
-        deriveServiceState(nextState, unwrap(state)) as StateFrom<TMachine>
+        deriveServiceState(
+          { ...nextState, actions: undefined },
+          unwrap(state)
+        ) as StateFrom<TMachine>
+      );
+      setState(
+        deriveServiceState(
+          { ...nextState, actions: nextState.actions },
+          unwrap(state)
+        ) as StateFrom<TMachine>
       );
     });
```

I don't really believe that this is the right solution here. I'm not super familiar with this reconciliation logic... I think that ideally, it should create a copy (a deep one?) of the initial state and later on only write to it based on the fresh state. I've tried to make a copy of `state.actions` (only the array itself) before passing that to the reconciling function but that didn't yield the expected results.

Perhaps @GoldingAustin could advise here as he is way more intimate with this code.

**Comment by Andarist** [comment]
@GoldingAustin would you be able to check out what's going on here?

**Comment by GoldingAustin** [comment]
> @GoldingAustin would you be able to check out what's going on here?

Yeah I'll take a look this week and hopefully have a solution by this weekend!

**Comment by parker-crabnebula** [comment]
Would [reconcile](https://www.solidjs.com/docs/latest/api#reconcile) be of any use?

**Comment by atilafassina** [comment]
> @parker-crabnebula said:
> Would [reconcile](https://www.solidjs.com/docs/latest/api#reconcile) be of any use?

I agree with this idea. Reconcile would allow to diff the entire object and update only the values that changed. It seems the right way to go about this.

But I may be missing something big on the XState internals.

Like @Andarist said:
> I don't really believe that this is the right solution here. I'm not super familiar with this reconciliation logic


I'll go on a limb and say that @erikras is probably a person with the right experience intersection to pitch in

![Thor saying "because that's what heroes do](https://github.com/statelyai/xstate/assets/2382552/c0086863-a03f-4d58-8055-4b5819bcc9f9)

**Comment by atilafassina** [comment]
funny enough, XState is even mentioned in the [`reconcile` tutorial](https://www.solidjs.com/tutorial/stores_immutable?solved):

> Stores are most often created in Solid using Solid's Store proxies. Sometimes we wish to interface with immutable libraries like Redux, Apollo, or XState and need to perform granular updates against these.

[`createImmutable`](https://primitives.solidjs.community/package/immutable) isn't part of the Solid core and goes the other way around, turning and immutable object into a store. I guess this allows you to manually perform granular updates...

From what I'm seeing, this problem is better addressed with `reconcile()`, that can be used in a store from `createImmutable` anyway...

> Either way, this issue was created before we released v4 and v5 could actually impact this quite a bit. So whatever I found in https://github.com/statelyai/xstate/issues/3925#issuecomment-1484837754 is probably heavily outdated and this has to be investigated from scratch.

👍 I'll go read that one then!

**Comment by erikras** [comment]
[walks out on stage]

[takes a bow]

[walks back off stage]

**Comment by Andarist** [comment]
This is embarrassing... we had a bug in a test case replicating this issue. The core of the test case itself was OK but lacked an extra `await sleep(50)` (note that it wouldn't pass with XState v4 even with that). Since it didn't work in v4 I didn't revisit this test code in v5 and trusted that it failed for some legitimate reason. It turns out that this was a mistake. We should be able to prepare a new `@xstate/solid` release in the coming days - one that will be compatible with XSatte v5.

**Comment by eecolella** [comment]
Hey there! Just want to ask if there's any update on this issue and if I can help in any way.

My understanding is that there is just a test that needs fixing in this PR https://github.com/statelyai/xstate/pull/4680, is that correct?

**Comment by Andarist** [comment]
@eecolella I plan to release the new `@xstate/solid` version tomorrow

**Comment by Andarist** [comment]
I believe that the issue itself was fixed by https://github.com/statelyai/xstate/pull/4059 . I added the test case for this in https://github.com/statelyai/xstate/pull/4468 and I'm working on the `@xstate/solid` release just now.

**Comment by GoldingAustin** [comment]
> funny enough, XState is even mentioned in the [`reconcile` tutorial](https://www.solidjs.com/tutorial/stores_immutable?solved):
> 
> > Stores are most often created in Solid using Solid's Store proxies. Sometimes we wish to interface with immutable libraries like Redux, Apollo, or XState and need to perform granular updates against these.
> 
> [`createImmutable`](https://primitives.solidjs.community/package/immutable) isn't part of the Solid core and goes the other way around, turning and immutable object into a store. I guess this allows you to manually perform granular updates...
> 
> From what I'm seeing, this problem is better addressed with `reconcile()`, that can be used in a store from `createImmutable` anyway...
> 
> > Either way, this issue was created before we released v4 and v5 could actually impact this quite a bit. So whatever I found in [#3925 (comment)](https://github.com/statelyai/xstate/issues/3925#issuecomment-1484837754) is probably heavily outdated and this has to be investigated from scratch.
> 
> 👍 I'll go read that one then!

I'm very excited if the current implementation can be simplified to use Solid's store+utils without workarounds! 

To add context to the [original integration](https://github.com/statelyai/xstate/pull/2932), there were many attempts (over almost a year) to make `createStore` and `reconcile` work. There are several features beyond state context that make XState powerful that did not mesh well with Solid's stores initially. The `createImmutable` hook in @xstate/solid is based on a prototype Ryan shared before it was part of the primitives package; it only requires a single deep clone rather than a deep clone on every setState+reconcile and ended up being comparable in speed and more memory efficient in larger projects.
