### ISSUE TITLE
Bug: Unexpected re-entry with an internal transition in v5

### ISSUE THREAD

**Issue by rlaffers** [statelyai/xstate#4218]
### Description

An internal transition specified with `reenter: false` still caused the entry action to be executed.

```javascript
const machine = createMachine({
	id: 'root',
	initial: 'Ready',
	states: {
		Ready: {
			entry: () => console.log('enter Ready'),
	    	on: {
	        	TOGGLE: {
					target: "#root.Ready",
					reenter: false, // 🪲 despite this, the Ready state will be re-entered
		        }
			}
		}
	}
})
```

### Expected result

When the machine receives a TOGGLE event, the "Ready" state should not be reentered. There should be a single log "enter Ready".

### Actual result

The Ready state is re-entered even when the transition is explicitly marked as internal with `reenter: false`.
"enter Ready" is logged twice (once on xstate.init, the second time on TOGGLE).

### Reproduction

https://codesandbox.io/s/bitter-star-63z86x

### Additional context

For comparison, XState v4 did not execute the entry action in this exact scenario. Compare with:
https://codesandbox.io/s/focused-monad-4f3v9d

**Comment by Andarist** [comment]
If we treat `reenter` as just a renamed `internal` then the current behavior is correct (according to SCMXL):
> The behavior of transitions with 'type' of "internal" is identical, except in the case of a transition whose source state is a compound state and whose target(s) is a descendant of the source. In such a case, an internal transition will not exit and re-enter its source state, while an external one will, as shown in the example below.

Since the target here is not a descendant of the source (it is the source itself), the transition reenters the source.

It is quite confusing though - especially with the name that we have chosen for this transition property (`reenter`). So I think that it would be good to diverge from SCXML here.

**Comment by rlaffers** [comment]
Hmm, your call guys. On hand, sticking to the standard should be quite important. On the other hand, this is indeed confusing. Also, changing this behavior makes migration to v5 more difficult.


It wouldn't be the only diversion by the way. The spec says:
>  The behavior of a transition with 'type' of "external" (the default) ...

Whereas, xstate v5 defaults to internal transitions (reenter:false).

**Comment by rlaffers** [comment]
Well, the spec later says:
> Note that this is different from a <transition> whose 'target' is its source state. In the latter case, the state is exited and reentered, triggering execution of its <onentry> and <onexit> executable content.

It seems that the spec explicitly says the state should be re-entered in this case.

**Comment by Andarist** [comment]
> It wouldn't be the only diversion by the way.

I don't think that this one is a big diversion. It's merely a different default but the rest of the semantics related to this are currently the same. If we treat that as a diversion then the v4 behavior of choosing the default `internal` value based on how the `target`'s descriptor was written was also a diversion.

There are still other subtle differences from SCXML - ones that we can't even fix. For instance, the state composition works differently because our root is already a state whereas in SCXML you could have **multiple** root states. That's not achievable in XState since a list of XML elements just works slightly differently than a keyed object in this regard.

Overall, I don't think that 100% compliance with SCXML should even be our current goal. It's nice to be inspired by it and it answers some unobvious questions for us but it's a standard that has not been updated for years and one that wasn't designed with strict static types in mind. We need some liberty to improve upon things.

**Comment by rlaffers** [comment]
I agree, let's be pragmatic. In your discussion with David you pointed out an important edge case where it indeed feels bad that a transition targeting the source state causes the re-entry and thus the actor would be restarted unexpectedly:
```javascript
{
  initial: 'a',
  states: {
    a: {
      invoke: {
        src: 'fooActor'
      },
      on: {
        NEXT: {
          target: 'a',
          internal: true
        }
      }
    }
  }
}
```
I fully agree that it should not re-enter, even though we diverge from the spec a little bit.

**Comment by rlaffers** [comment]
And like it was said, the semantics of `reenter` does not need to be the same as that of `internal`.
