### ISSUE TITLE
[BUG] Cleanup spawned actors from the "system"

### ISSUE THREAD

**Issue by KrisCoulson** [statelyai/xstate#4453]
## Bug or feature request?
BUG

## Description:
System IDs are not cleaned up when they use a system ID that has already been used. xstate throws an error.
Note that this reproduction doesn't stop the machine first by putting it in to a final state but I have tried that as well and it behaves the same way. Once a system id has been used there is no way to clean it up.

## (Bug) Expected result:
I should be able to add an item give it a system id and remove that item from the system and then readd the item with the same id.

## (Bug) Actual result:
Revceiving an error with - "Actor with system ID 'item:1' already exists."

## (Bug) Potential fix:
Cleanup spawned actors when they are removed.

## Link to reproduction or proof-of-concept:
Click the add button. remove the item. click the add button again.
https://codesandbox.io/s/xstate-cleanup-system-id-error-nwgz2f

**Comment by davidkpiano** [comment]
Okay, so it turns out the `systemId` will only be cleared out when the actor is **stopped**, which it wasn't in the reproduction.

Here is the updated, working repro where the actor is stopped before it's filtered out: https://codesandbox.io/s/xstate-cleanup-system-id-error-forked-zhhw94?file=/src/index.js

In the future, we may make a more convenient way to do this.
