### ISSUE TITLE
Bug: [v5] typescript warning due to non-existing awaitable return type signature for actor.send 

### ISSUE THREAD

**Issue by bhvngt** [statelyai/xstate#4504]
### Description

My understanding is that when triggering an event via `send` method of an actor, we need to await the call if the event happens to invoke a child actor.

The code works fine. However, typescript complains with the following warning

![image](https://github.com/statelyai/xstate/assets/79074469/4aef1e4e-b28f-434f-9d69-b5e3a29e363f)

### Expected result

Expecting `actor.send` to return `Awaitable<void>`.

### Actual result

Currently typescript complains due to incorrect signature.

### Reproduction

https://stackblitz.com/edit/xstate-v5-bug?file=src%2Fcounter.ts&terminal=dev

**Comment by Andarist** [comment]
`.send` doesn't return a promise and isn't meant to. There is no particular "response" which you could await here. The received event is added to the internal queue and if the queue is empty then it's processed right away. If the queue is not empty then it isn't processed right away but it will still be processed as soon as possible, within the same stack (the queue is guaranteed to be emptied before we "yield" to the main event loop of the runtime)

**Comment by bhvngt** [comment]
Thanks for explanation @Andarist. 

In my [example](https://stackblitz.com/edit/xstate-v5-bug?file=src%2Fcounter.ts&terminal=dev), I see that machine subscription gives different state transition value for `with await` and `without await` calls. Is this expected?

Is the assumption that typical event calls will always end up with some sort of `yield` in the event loop?

**Comment by Andarist** [comment]
> In my [example](https://stackblitz.com/edit/xstate-v5-bug?file=src%2Fcounter.ts&terminal=dev), I see that machine subscription gives different state transition value for with await and without await calls. Is this expected?

It's just how JavaScript runtime works. Your actor is a promise and even though its final value doesn't depend on anything async it's still wrapped into a promise. Promises **always** resolve in microtasks and won't ever resolve synchronously. So when this actor gets instantiated it can't "notify" the parent immediately - it will happen "in the next tick".

Similarly, when you `await` - even though you don't await anything asynchronous - you are implicitly creating a new promise there and it gets appended to the microtask loop. But at this time one job is already there (completion of your actor) so it gets **queued** after it. And then that first job gets handled first, it manages to notify the parent, the machine transitions, etc. And only after that your second job (the one that you created by `await`ing) resolves and it's able to read the updated values.

It's a timing issue~ related to how the runtime works. It's somewhat accidental that you see those updated values there. It happens because both of those microtasks are "immediate" (but still queued one after another since JS is single-threaded). You wouldn't observe the same behavior if your actor would actually do something asynchronously before completing.

**Comment by bhvngt** [comment]
Thank you so much @Andarist for your in depth explanation 👍. Make complete sense to me now..
