### ISSUE TITLE
Bug: reenter doesn't work if target not set on transition

### ISSUE THREAD

**Issue by nottud** [statelyai/xstate#4722]
### XState version

XState version 5

### Description

The reenter property seems to be ignored if the target is not set.

### Expected result

The reenter property should be acted on as if the target is set to the current state

### Actual result

The renter property is ignored and nothing triggering on exit or entering occurs. In my case the invoke is ignored.

### Reproduction

See additional context

### Additional context

Call your state "test" and our event EVENT:

```
EVENT: {
   target: 'test',
   reenter: true
}
```
^^^ This works ^^^
```
EVENT: {
   reenter: true
}
```
^^^ This does not ^^^

**Comment by davidkpiano** [comment]
Targetless transitions do not have a target to reenter. I would say this is by design - you should specify a `target` if you set `reenter: true`.

My thinking is that if you don't, and you want `reenter: true` to implicitly mean "reenter the same state node if `target` is not defined", then now an undefined `target` can mean two different things:

- No target
- The same target if `reenter: true`

Which is too ambiguous IMO. It's better if undefined `target` _always_ means targetless.
