### ISSUE TITLE
Bug: fromObservable emits undefined as first value

### ISSUE THREAD

**Issue by ivankoleda** [statelyai/xstate#4799]
### XState version

XState version 5

### Description

`fromObservable` always emits undefined as the first value and then emits correct values.

```ts
import { interval } from 'rxjs';

const secondLogic = fromObservable(() => interval(1000));

const secondActor = createActor(secondLogic);

secondActor.subscribe((snapshot) => {
  console.log(snapshot.context);
  // This code produces 
  // undefined, 0, 1, 2, 3 ...
  // instead of
  // 0, 1, 2, 3 ...
});

secondActor.start();
```

xstate v5.9.1
rxjs v7.8.1

### Expected result

0, 1, 2, 3 ...

### Actual result

undefined, 0, 1, 2, 3 ...

### Reproduction

https://stackblitz.com/edit/vitejs-vite-memba2?file=src%2Fmain.ts

### Additional context

Docs section with the code snippet.
https://stately.ai/docs/observable-actors#observable-actor-logic

**Comment by davidkpiano** [comment]
This is expected behavior because the actor needs to be in _some_ initial state when it is started. In the observable actor's case, the initial state is that nothing was produced yet from the actor, which is represented by `snapshot.context === undefined`.

Also, if you were to read the snapshot of the actor before it produced anything, then you _would_ expect `undefined`.

If you weren't using XState, this would be analogous to this:

```ts
let currentValue = undefined; // we don't know what the first value is!

interval$.subscribe(val => {
  currentValue = val;
});

currentValue; // undefined
```

**Comment by ivankoleda** [comment]
Thanks for the explanation.
So if I understand correctly, there is no way to have a different initial value given an approach with `setup` function.

```ts
setup({
  actors: {
    intervals: fromObservable(() => interval(1000)),
  },
}).createMachine({
  invoke: {
    src: 'intervals',
    onSnapshot: [], // undefined will always be initial value and there has to be a runtime check
  },
});
```

Can see the confirmation to this in type definitions:

```ts
export type ObservableSnapshot<TContext, TInput extends NonReducibleUnknown> = Snapshot<undefined> & {
    context: TContext | undefined;
    input: TInput | undefined;
    _subscription: Subscription | undefined;
};
```

I'm probably stating the obvious. Just thought I missed something in docs and there was a way to not have a runtime check for `undefined` in `onSnapshot` handlers.

**Comment by davidkpiano** [comment]
The problem is that observables are conceptually async; even if the first value comes back immediately, you must treat it as async. If observables had a notion of a synchronous initial value, we could use that (e.g. some sort of `obs$.getInitialValue()`, but this is not a concept in observables.

A potential idea may be to add something like this to XState:

```ts
const logic = fromObservable(() => interval$, { startWith: 0 });
```

I'll continue to think about this.
