### ISSUE TITLE
Persisting Machine State with Invoked Child Machine Does Not Pass Context

### ISSUE THREAD

**Issue by wilson51492** [statelyai/xstate#720]
**Description**
When using `resolveState` to start a machine from a specific state (as descibed here https://xstate.js.org/docs/guides/states.html#persisting-state), it appears that if the current state invokes a child machine, the `data` prop on the `invoke` prop will not be called.  This means that the child machine cannot recieve the context from the parent machine

**Expected Result**
When using `resolveState` and passing the result into `start`, if the current state includes an `invoke` prop, the `data` prop of `invoke` should be called.

**Actual Result**
When using `resolveState` and passing the result into `start`, if the current state includes an `invoke` prop, the `data` prop of `invoke` is not called and the child machine is not invoked with the expected context.

**Reproduction**
https://codesandbox.io/s/xstate-example-template-qdyrr

**Additional context**
I am trying to make it so that if my application goes down, the state machine can be restored to where it was, and the current child machine is re-invoked as expect.

Additionally, It would be fantastic if we could use the same pattern to invoke child machines in a specific state, so that if the applicaiton does down in the middle of a child machine it can be restored to that point instead of being forced to start at the initial state of the child machine.

**Comment by nikogosovd** [comment]
What is the current state of this bug?

Also, it would be great if we could restore the entire statechart with nested machines from a state where some nested machine has stopped (the additional context of the bug report is saying exactly that).

I'm using xstate on the server and the statechart has some nested machines, and I want to restore from any state the statechart left in.

**Comment by davidkpiano** [comment]
It's a tricky bug/enhancement to do because there is a delicate balance between what XState should do and what should be done in implementation details.

For example, if a child machine starts by sending a POST request, you probably don't want it to resend that POST request when you restore the state, right?

Still thinking through this. It's not as simple as "just restore all nested machines" - that can have unintended consequences.

**Comment by nikogosovd** [comment]
> For example, if a child machine starts by sending a POST request, you probably don't want it to resend that POST request when you restore the state, right?

Of course, I don't. 

Yeah, I feel that this feature looks tricky and possibly includes a huge refactoring. For me, this feature will be useful because child machines have isolated contexts and when the child machine is done, its context doesn't pollute parent' context (or does it in a controlled way if I want it).

When I understand how the context may be completely rewritten (https://github.com/davidkpiano/xstate/issues/989) I will able to use the only one root machine with complex nested states (instead of multiple nested machines) where a specific state when done, will clear the context by the assign action.

**Comment by lukenofurther** [comment]
@davidkpiano how difficult would it be to add an option to services to optionally allow them to be reinvoked when a parent state containing them is restored?

**Comment by davidkpiano** [comment]
> @davidkpiano how difficult would it be to add an option to services to optionally allow them to be reinvoked when a parent state containing them is restored?

That's something I'm (slowly) working on, might have to wait for v5 though. I'm trying to determine if reinvoking should be opt-in or opt-out behavior. What are your thoughts?

**Comment by lukenofurther** [comment]
> That's something I'm (slowly) working on, might have to wait for v5 though. I'm trying to determine if reinvoking should be opt-in or opt-out behavior. What are your thoughts?

In terms of backwards-compatibility I'd say opt-in. Disregarding  backwards compatibiity, it depends on the type of service. If it's a child machine you'd always want them to be re-invoked. I'm only using this for child machines so don't have any other context for the use of services to draw upon.

Thinking specifically about restoring child machines, there are a couple of complications. You might already be aware of these but just in case you're not:

1. The child machine may have its own persisted state, so there needs to be some way to hook into the starting of the child service to start it with in that persisted state. Currently the starting of child machine services is handled inside the black box of the interpreter. I've resorted to using callbacks to achieve restoration of the child machine.

2. The child service may have been started in a previous state, in which case its invokation isn't included in the restored state's list of starting actions. However, I believe it is still included in the list of activities at least.

I can understand why you want to wait until the next major version. That'll give you a freer reign to do things like for example breaking out child machines into their own category, if that would be warranted.

**Comment by erickreutz** [comment]
Has there been any progress made here?

**Comment by davidkpiano** [comment]
> Has there been any progress made here?

We are overhauling how actors are invoked/spawned in V5, and are still determining the best strategy for restoring actors. We hope to have a preview of this within a few weeks.

**Comment by davidkpiano** [comment]
Related: https://github.com/statelyai/xstate/pull/3743

**Comment by puelocesar** [comment]
We found out that we can restore the children state machine by having a duplicated Interpreter. So we have something like this:

```
const mainService = useInterpret(
    mainMachine,
    {
      context: {...},
    },
    (state) => {
      // save state of main machine
    },
  );

  const childService = useInterpret(
    childMachine,
    {
      context: childMachineContext,
    },
    (state) => {
      // save state of child machine
    },
  );
```

And if there's an already persisted state, we start the machine with it:

```
const calculatedInitialState = mainService.machine.getInitialState(restoredMainState);
mainService.start(calculatedInitialState);

const calculatedInitialStateChild = childService.machine.getInitialState(restoredMainStateChild);
childService.start(calculatedInitialStateChild);
```

This kind of works, because it properly restores my child machines to the point where they were, but it has the obvious problem that now they are duplicated, as they are created manually with useInterpret and invoked by the main machine.

This causes a bunch of other issues, so I wonder if there's any alternative way of achieving this without having to wait for a future version of XState including the related PR #3743

**Comment by davidkpiano** [comment]
Persisting child machines now works as expected in `xstate@beta`. See the updated example: https://codesandbox.io/s/xstate-example-template-forked-7btxqv?file=/src/index.js

**Comment by veeramarni** [comment]
@davidkpiano  do we have a solution for multiple child references? We can save the state of each child and try restore it if the `spawn` function has a way to restore it.

```
        actions: {
            spawnRecords: assign((context, event: any) => {
                if (context.spawnedTimeSlots) {
                    return;
                }
                const spawnedTimeSlots = ((context.records as any) || []).reduce((acc, record, index) => {
                    acc[record.id] = spawn(recordStatusMachine.withContext(record));
                    return acc;
                }, {});
                return { spawnedTimeSlots };
            }),
...
}
```

Also I have a second question, when restoring the `state`, if there is `on entry` function, it will get re-executed how can we avoid it?
