### ISSUE TITLE
Delay functions get resolved even when a transient transition is going to happen first.

### ISSUE THREAD

**Issue by tanishalfelven** [statelyai/xstate#922]
**Description**
In a state node when there is both a transient transition out of the state and there is also a delay, the delay time is resolved even when the transient transition should be taken first.

**Expected Result**
The delay function should not get called unless a delay is being taken.

**Actual Result**
The delay is resolved even though the transient transition is taken.

**Reproduction**
[codesandbox](https://codesandbox.io/s/broken-leaf-x01iu)

**Additional context**
Working in latest version of xstate available on codesandbox.

Thanks!

**Comment by Andarist** [comment]
This is due to the fact of how things are currently implemented. It shouldn't cause any problems as your `delay` should really be a pure function - we only execute it unnecessarily in this case.

I'm afraid that it might not be worth for us to fix this in v4, but we have started to work on v5 which will have many parts of the implementation reimplemented - we should have this fixed then.

**Comment by davidkpiano** [comment]
As mentioned, this is working in the latest version of `xstate`.
