### ISSUE TITLE
@xstate/test removes function event params

### ISSUE THREAD

**Issue by tivac** [statelyai/xstate#982]
**Description**

We use functions for a lot of our mocks, so I was trying to set up a way to execute our mocked behavior in an event via `exec : (ctx, event) => event.mock()` and providing multiple different mocks as `cases` to represent the different ways the event could go. Not convinced that's the right way to treat it, but I found a surprising behavior regardless.

**Expected Result**

The functions specified in the event objects passed to `cases` would exist inside the event object passed to `exec`.

**Actual Result**

Function properties are stripped from the event objects. Arrays & Objects come through fine, but even their children that are functions are stripped by the time `exec` sees the event.

**Reproduction**
https://codesandbox.io/s/xstatetest-cases-function-removal-bdnxr

**Additional context**

- `@xstate/test@0.3.0`
- `xstate@4.7.8`

**Comment by davidkpiano** [comment]
Since events should only contain serializable (JSON-like) data, the better way to model this would be to add some sort of meta property on the event case, such as `{ color: 'blue' }` and in `exec: ...`, execute some function based on that `color` property.

However, I'm ensuring that all properties/values of the event object stay intact (even for non-serializable values) in the next upcoming version of `@xstate/graph` and `@xstate/test` 👍
